#!/usr/bin/env python3
"""
Generate reminders-cli.m from ReminderKit private API.

USAGE:
    python3 generate-cli.py > reminders-cli.m
    # Then: make reminders-cli

MAINTENANCE:
    This generator produces reminders-cli.m — the Objective-C source for the
    reminders CLI. The generated code wraps Apple's private ReminderKit framework,
    exposing each property/setter as a CLI command with JSON output.

    To add a new READ property:
        1. Add an entry to REMINDER_READ_PROPS below
        2. Format: "objcPropertyName": ("jsonKey", "type_hint")
        3. Type hints: "string", "bool", "bool_getter", "int", "uint",
                       "date", "datecomps", "objid", "set_hashtags"
        4. Regenerate: python3 generate-cli.py > reminders-cli.m && make reminders-cli

    To add a new WRITE operation (setter):
        1. Add an entry to REMINDER_WRITE_OPS below
        2. Format: "cli-flag": ("setterSelector:", "arg_type")
        3. Arg types: "string", "bool", "int", "uint", "datecomps"
        4. For no-arg methods (like removeFromParentReminder), add to SPECIAL_WRITE_OPS
        5. Regenerate

    To discover new properties/methods:
        make remkit-inspect && ./remkit-inspect 2>&1 | less

    Architecture:
        remkit-inspect.m  →  dumps ObjC runtime properties/methods (discovery tool)
        generate-cli.py   →  generates reminders-cli.m from config dicts (this file)
        reminders-cli.m   →  AUTO-GENERATED, do not edit manually
        Makefile           →  builds everything, `make generate` regenerates
"""


# --- Configuration ---

# Properties to expose on REMReminder (read)
# Maps property name -> (json_key, type_hint)
# type_hint: "string", "bool", "int", "uint", "date", "objid", "set_hashtags", "datecomps"
REMINDER_READ_PROPS = {
    "titleAsString":      ("title",          "string"),
    "notesAsString":      ("notes",          "string"),
    "completed":          ("completed",      "bool_getter"),  # getter is isCompleted
    "priority":           ("priority",       "uint"),
    "flagged":            ("flagged",        "int"),
    "allDay":             ("allDay",         "bool"),
    "isOverdue":          ("isOverdue",      "bool"),
    "isRecurrent":        ("isRecurrent",    "bool"),
    "objectID":           ("id",             "objid"),
    "listID":             ("listID",         "objid"),
    "parentReminderID":   ("parentID",       "objid"),
    "dueDateComponents":  ("dueDate",        "datecomps"),
    "startDateComponents":("startDate",      "datecomps"),
    "creationDate":       ("createdAt",      "date"),
    "lastModifiedDate":   ("modifiedAt",     "date"),
    "completionDate":     ("completedAt",    "date"),
    "hashtags":           ("hashtags",       "set_hashtags"),
    "timeZone":           ("timeZone",       "string"),
}

# Setters to expose on REMReminderChangeItem (write via update command)
# Maps cli_flag -> (setter_method, arg_type)
# arg_type: "string", "bool", "uint", "int", "datecomps", "none"
REMINDER_WRITE_OPS = {
    "title":        ("setTitleAsString:",       "string"),
    "notes":        ("setNotesAsString:",       "string"),
    "completed":    ("setCompleted:",           "bool"),
    "priority":     ("setPriority:",            "uint"),
    "flagged":      ("setFlagged:",             "int"),
    "due-date":     ("setDueDateComponents:",   "datecomps"),
    "start-date":   ("setStartDateComponents:", "datecomps"),
}

# Special write operations (not simple setters)
SPECIAL_WRITE_OPS = {
    "remove-parent": "removeFromParentReminder",
    "remove-from-list": "removeFromList",
}


def generate_header():
    return '''// AUTO-GENERATED by generate-cli.py — do not edit manually
// Regenerate: ./remkit-inspect 2>&1 | python3 generate-cli.py > reminders-cli.m

#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <objc/message.h>

// --- Framework Loading ---

static Class REMStoreClass;
static Class REMSaveRequestClass;
static Class REMSubtaskCtxClass;
static Class REMListSectionCIClass;

static void loadFramework(void) {
    [[NSBundle bundleWithPath:@"/System/Library/PrivateFrameworks/ReminderKit.framework"] load];
    REMStoreClass = NSClassFromString(@"REMStore");
    REMSaveRequestClass = NSClassFromString(@"REMSaveRequest");
    REMSubtaskCtxClass = NSClassFromString(@"REMReminderSubtaskContextChangeItem");
    REMListSectionCIClass = NSClassFromString(@"REMListSectionChangeItem");
}

static id getStore(void) {
    return ((id (*)(id, SEL, BOOL))objc_msgSend)(
        [REMStoreClass alloc], sel_registerName("initUserInteractive:"), YES);
}

// --- Helpers ---

static void errorExit(NSString *msg) {
    fprintf(stderr, "Error: %s\\n", [msg UTF8String]);
    exit(1);
}

static NSString *objectIDToString(id objID) {
    if (!objID) return nil;
    return [[objID description] stringByReplacingOccurrencesOfString:@"<" withString:@""]
        ? [objID description] : @"(unknown)";
}

static NSString *dateToISO(NSDate *date) {
    if (!date) return nil;
    NSISO8601DateFormatter *fmt = [[NSISO8601DateFormatter alloc] init];
    return [fmt stringFromDate:date];
}

static NSString *dateCompsToString(NSDateComponents *comps) {
    if (!comps) return nil;
    NSCalendar *cal = [NSCalendar currentCalendar];
    NSDate *date = [cal dateFromComponents:comps];
    if (date) return dateToISO(date);
    // Fallback: manual formatting
    return [NSString stringWithFormat:@"%04ld-%02ld-%02ld",
        (long)[comps year], (long)[comps month], (long)[comps day]];
}

static NSDateComponents *stringToDateComps(NSString *str) {
    // Parse ISO date string like "2026-03-15" or "2026-03-15T10:00:00"
    NSDateComponents *comps = [[NSDateComponents alloc] init];
    NSArray *parts = [str componentsSeparatedByString:@"T"];
    NSArray *dateParts = [parts[0] componentsSeparatedByString:@"-"];
    if (dateParts.count >= 3) {
        comps.year = [dateParts[0] integerValue];
        comps.month = [dateParts[1] integerValue];
        comps.day = [dateParts[2] integerValue];
    }
    if (parts.count > 1) {
        NSArray *timeParts = [parts[1] componentsSeparatedByString:@":"];
        if (timeParts.count >= 2) {
            comps.hour = [timeParts[0] integerValue];
            comps.minute = [timeParts[1] integerValue];
        }
    }
    return comps;
}

static void printJSON(id obj) {
    NSError *error = nil;
    NSData *data = [NSJSONSerialization dataWithJSONObject:obj
        options:NSJSONWritingPrettyPrinted | NSJSONWritingSortedKeys error:&error];
    if (error) errorExit([error localizedDescription]);
    printf("%s\\n", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding].UTF8String);
}

// --- List Helpers ---

static NSArray *fetchLists(id store) {
    NSError *error = nil;
    NSArray *lists = ((id (*)(id, SEL, id*))objc_msgSend)(
        store, sel_registerName("fetchEligibleDefaultListsWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Failed to fetch lists: %@", error]);
    return lists;
}

static id findList(id store, NSString *name) {
    NSArray *lists = fetchLists(store);
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *listName = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        if ([listName isEqualToString:name]) return list;
    }
    return nil;
}

static NSArray *fetchReminders(id store, id list, BOOL includeCompleted) {
    id listObjID = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("objectID"));
    NSError *error = nil;
    NSArray *all = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listObjID], &error);
    if (error) errorExit([NSString stringWithFormat:@"Failed to fetch reminders: %@", error]);
    if (includeCompleted) return all;
    NSMutableArray *incomplete = [NSMutableArray array];
    for (id rem in all) {
        BOOL done = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isCompleted"));
        if (!done) [incomplete addObject:rem];
    }
    return incomplete;
}

static id findReminder(id store, NSString *title, NSString *listName) {
    NSArray *lists;
    if (listName) {
        id list = findList(store, listName);
        if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
        lists = @[list];
    } else {
        lists = fetchLists(store);
    }
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, YES);
        for (id rem in rems) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            if ([t isEqualToString:title]) return rem;
        }
    }
    return nil;
}
'''


def generate_reminder_to_dict():
    """Generate the reminderToDict function from REMINDER_READ_PROPS."""
    lines = [
        'static NSDictionary *reminderToDict(id rem) {',
        '    NSMutableDictionary *dict = [NSMutableDictionary dictionary];',
        '',
    ]

    for prop, (json_key, type_hint) in REMINDER_READ_PROPS.items():
        sel = prop
        if type_hint == "string":
            lines.append(f'    @try {{')
            lines.append(f'        NSString *val_{json_key} = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("{sel}"));')
            lines.append(f'        if (val_{json_key}) dict[@"{json_key}"] = val_{json_key};')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "bool":
            lines.append(f'    @try {{')
            lines.append(f'        BOOL val_{json_key} = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("{sel}"));')
            lines.append(f'        dict[@"{json_key}"] = @(val_{json_key});')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "bool_getter":
            # completed has getter isCompleted
            lines.append(f'    @try {{')
            lines.append(f'        BOOL val_{json_key} = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isCompleted"));')
            lines.append(f'        dict[@"{json_key}"] = @(val_{json_key});')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "uint":
            lines.append(f'    @try {{')
            lines.append(f'        NSUInteger val_{json_key} = ((NSUInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("{sel}"));')
            lines.append(f'        dict[@"{json_key}"] = @(val_{json_key});')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "int":
            lines.append(f'    @try {{')
            lines.append(f'        NSInteger val_{json_key} = ((NSInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("{sel}"));')
            lines.append(f'        dict[@"{json_key}"] = @(val_{json_key});')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "objid":
            lines.append(f'    @try {{')
            lines.append(f'        id val_{json_key} = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("{sel}"));')
            lines.append(f'        if (val_{json_key}) dict[@"{json_key}"] = objectIDToString(val_{json_key});')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "date":
            lines.append(f'    @try {{')
            lines.append(f'        NSDate *val_{json_key} = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("{sel}"));')
            lines.append(f'        if (val_{json_key}) dict[@"{json_key}"] = dateToISO(val_{json_key});')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "datecomps":
            lines.append(f'    @try {{')
            lines.append(f'        NSDateComponents *val_{json_key} = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("{sel}"));')
            lines.append(f'        if (val_{json_key}) dict[@"{json_key}"] = dateCompsToString(val_{json_key});')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        elif type_hint == "set_hashtags":
            lines.append(f'    @try {{')
            lines.append(f'        NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));')
            lines.append(f'        if (tags && tags.count > 0) {{')
            lines.append(f'            NSMutableArray *tagNames = [NSMutableArray array];')
            lines.append(f'            for (id tag in tags) {{')
            lines.append(f'                NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));')
            lines.append(f'                if (name) [tagNames addObject:name];')
            lines.append(f'            }}')
            lines.append(f'            dict[@"{json_key}"] = tagNames;')
            lines.append(f'        }}')
            lines.append(f'    }} @catch (NSException *e) {{}}')
        lines.append('')

    lines.append('    return dict;')
    lines.append('}')
    return '\n'.join(lines)


def generate_commands():
    """Generate the command implementations."""
    return '''
// --- Commands ---

static int cmdLists(id store) {
    NSArray *lists = fetchLists(store);
    NSMutableArray *result = [NSMutableArray array];
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        id objID = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("objectID"));
        [result addObject:@{@"name": name ?: @"", @"id": objectIDToString(objID) ?: @""}];
    }
    printJSON(result);
    return 0;
}

static int cmdList(id store, NSString *listName, BOOL includeCompleted) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
    NSArray *rems = fetchReminders(store, list, includeCompleted);
    NSMutableArray *result = [NSMutableArray array];
    for (id rem in rems) {
        [result addObject:reminderToDict(rem)];
    }
    printJSON(result);
    return 0;
}

static int cmdGet(id store, NSString *title, NSString *listName) {
    id rem = findReminder(store, title, listName);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);

    NSMutableDictionary *dict = [reminderToDict(rem) mutableCopy];

    // Add subtasks
    id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
    NSString *parentIDStr = objectIDToString(parentObjID);
    id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
    NSError *error = nil;
    NSArray *allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listID], &error);

    NSMutableArray *subtasks = [NSMutableArray array];
    for (id sub in allInList) {
        id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
        if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
            [subtasks addObject:reminderToDict(sub)];
        }
    }
    if (subtasks.count > 0) dict[@"subtasks"] = subtasks;

    printJSON(dict);
    return 0;
}

static int cmdSubtasks(id store, NSString *title, NSString *listName) {
    id rem = findReminder(store, title, listName);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);

    id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
    NSString *parentIDStr = objectIDToString(parentObjID);
    id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
    NSError *error = nil;
    NSArray *allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listID], &error);

    NSMutableArray *subtasks = [NSMutableArray array];
    for (id sub in allInList) {
        id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
        if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
            [subtasks addObject:reminderToDict(sub)];
        }
    }
    printJSON(subtasks);
    return 0;
}

static int cmdAdd(id store, NSString *title, NSString *listName, NSDictionary *opts) {
    id list = listName ? findList(store, listName) : [fetchLists(store) firstObject];
    if (!list) errorExit(@"No list found");

    id listChangeItem = nil;
    // Get the list change item from save request
    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    id newRem = ((id (*)(id, SEL, id, id))objc_msgSend)(
        saveReq, sel_registerName("addReminderWithTitle:toListChangeItem:"),
        title, listCI);

    if (!newRem) errorExit(@"Failed to create reminder");

    // Apply optional properties
''' + generate_add_setters() + '''

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    // Re-fetch and return
    id created = findReminder(store, title, listName);
    if (created) printJSON(reminderToDict(created));
    else fprintf(stderr, "Created (but could not re-fetch)\\n");
    return 0;
}

static int cmdCreateList(id store, NSString *name) {
    // Get default account from the first list
    NSArray *lists = fetchLists(store);
    if (lists.count == 0) errorExit(@"No accounts found");
    id account = ((id (*)(id, SEL))objc_msgSend)(lists[0], sel_registerName("account"));

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id accountCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateAccount:"), account);

    id newList = ((id (*)(id, SEL, id, id, id))objc_msgSend)(
        saveReq, sel_registerName("addListWithName:toAccountChangeItem:listObjectID:"),
        name, accountCI, nil);

    if (!newList) errorExit(@"Failed to create list");

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"name": name, @"created": @YES});
    return 0;
}

static int cmdRenameList(id store, NSString *oldName, NSString *newName) {
    id list = findList(store, oldName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", oldName]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    id storage = ((id (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("storage"));
    ((void (*)(id, SEL, id))objc_msgSend)(storage, sel_registerName("setName:"), newName);

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"oldName": oldName, @"newName": newName, @"renamed": @YES});
    return 0;
}

static int cmdDeleteList(id store, NSString *name) {
    id list = findList(store, name);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", name]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    ((void (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("removeFromParent"));

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"name": name, @"deleted": @YES});
    return 0;
}

static int cmdAddSubtask(id store, NSString *parentTitle, NSString *childTitle, NSString *listName) {
    id parentRem = findReminder(store, parentTitle, listName);
    if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found: %@", parentTitle]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id parentCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), parentRem);

    id subtaskCtx = ((id (*)(id, SEL))objc_msgSend)(parentCI, sel_registerName("subtaskContext"));
    if (!subtaskCtx) {
        subtaskCtx = ((id (*)(id, SEL, id))objc_msgSend)(
            [REMSubtaskCtxClass alloc], sel_registerName("initWithReminderChangeItem:"), parentCI);
    }

    id newSub = ((id (*)(id, SEL, id, id))objc_msgSend)(
        saveReq, sel_registerName("addReminderWithTitle:toReminderSubtaskContextChangeItem:"),
        childTitle, subtaskCtx);
    if (!newSub) errorExit(@"Failed to create subtask");

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    id created = findReminder(store, childTitle, listName);
    if (created) printJSON(reminderToDict(created));
    else fprintf(stderr, "Created (but could not re-fetch)\\n");
    return 0;
}

static int cmdAddTag(id store, NSString *title, NSString *tagName, NSString *listName) {
    id rem = findReminder(store, title, listName);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    id hashtagCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("hashtagContext"));
    if (!hashtagCtx) errorExit(@"Failed to get hashtag context");

    // type 0 = normal tag
    ((void (*)(id, SEL, NSUInteger, id))objc_msgSend)(
        hashtagCtx, sel_registerName("addHashtagWithType:name:"), (NSUInteger)0, tagName);

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    id updated = findReminder(store, title, listName);
    if (updated) printJSON(reminderToDict(updated));
    else printJSON(@{@"title": title, @"tagAdded": tagName});
    return 0;
}

static int cmdRemoveTag(id store, NSString *title, NSString *tagName, NSString *listName) {
    id rem = findReminder(store, title, listName);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    id hashtagCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("hashtagContext"));
    if (!hashtagCtx) errorExit(@"Failed to get hashtag context");

    // Find the hashtag object by name from the reminder's existing hashtags
    NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
    id tagToRemove = nil;
    for (id tag in tags) {
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
        if ([name isEqualToString:tagName]) { tagToRemove = tag; break; }
    }
    if (!tagToRemove) errorExit([NSString stringWithFormat:@"Tag not found: %@", tagName]);

    ((void (*)(id, SEL, id))objc_msgSend)(hashtagCtx, sel_registerName("removeHashtag:"), tagToRemove);

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    id updated = findReminder(store, title, listName);
    if (updated) printJSON(reminderToDict(updated));
    else printJSON(@{@"title": title, @"tagRemoved": tagName});
    return 0;
}

static int cmdListSections(id store, NSString *listName) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);

    // Try to fetch sections from the list
    NSMutableArray *result = [NSMutableArray array];
    @try {
        id sections = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("sections"));
        if (sections) {
            for (id section in sections) {
                NSString *name = ((id (*)(id, SEL))objc_msgSend)(section, sel_registerName("canonicalName"));
                id objID = ((id (*)(id, SEL))objc_msgSend)(section, sel_registerName("objectID"));
                NSMutableDictionary *d = [NSMutableDictionary dictionary];
                if (name) d[@"name"] = name;
                if (objID) d[@"id"] = objectIDToString(objID);
                [result addObject:d];
            }
        }
    } @catch (NSException *e) {
        fprintf(stderr, "Warning: could not enumerate sections: %s\\n", [[e reason] UTF8String]);
    }
    printJSON(result);
    return 0;
}

static int cmdCreateSection(id store, NSString *listName, NSString *sectionName) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    id sectionsCtx = ((id (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("sectionsContextChangeItem"));
    if (!sectionsCtx) errorExit(@"Failed to get sections context");

    id listObjID = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("objectID"));

    // Create a new section change item
    id newSection = ((id (*)(id, SEL, id, id, id))objc_msgSend)(
        [REMListSectionCIClass alloc],
        sel_registerName("initWithObjectID:displayName:insertIntoListChangeItem:"),
        nil, sectionName, listCI);

    if (!newSection) errorExit(@"Failed to create section");

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"list": listName, @"section": sectionName, @"created": @YES});
    return 0;
}
'''


def generate_update_command():
    """Generate the update command with all setter flags."""
    lines = [
        'static int cmdUpdate(id store, NSString *title, NSString *listName, NSDictionary *opts) {',
        '    id rem = findReminder(store, title, listName);',
        '    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);',
        '',
        '    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(',
        '        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);',
        '',
        '    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(',
        '        saveReq, sel_registerName("updateReminder:"), rem);',
        '',
    ]

    # Generate setter applications
    for flag, (setter, arg_type) in REMINDER_WRITE_OPS.items():
        if arg_type == "string":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("{setter}"), opts[@"{flag}"]);')
            lines.append(f'    }}')
        elif arg_type == "bool":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        BOOL val = [opts[@"{flag}"] isEqualToString:@"true"];')
            lines.append(f'        ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("{setter}"), val);')
            lines.append(f'    }}')
        elif arg_type == "uint":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        NSUInteger val = [opts[@"{flag}"] integerValue];')
            lines.append(f'        ((void (*)(id, SEL, NSUInteger))objc_msgSend)(changeItem, sel_registerName("{setter}"), val);')
            lines.append(f'    }}')
        elif arg_type == "int":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        NSInteger val = [opts[@"{flag}"] integerValue];')
            lines.append(f'        ((void (*)(id, SEL, NSInteger))objc_msgSend)(changeItem, sel_registerName("{setter}"), val);')
            lines.append(f'    }}')
        elif arg_type == "datecomps":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        NSDateComponents *comps = stringToDateComps(opts[@"{flag}"]);')
            lines.append(f'        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("{setter}"), comps);')
            lines.append(f'    }}')

    # Special operations
    for flag, method in SPECIAL_WRITE_OPS.items():
        lines.append(f'    if (opts[@"{flag}"]) {{')
        lines.append(f'        ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("{method}"));')
        lines.append(f'    }}')

    lines.extend([
        '',
        '    NSError *error = nil;',
        '    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(',
        '        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);',
        '    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);',
        '',
        '    // Re-fetch and return updated state',
        '    id updated = findReminder(store, opts[@"title"] ?: title, listName);',
        '    if (updated) printJSON(reminderToDict(updated));',
        '    else fprintf(stderr, "Updated successfully\\n");',
        '    return 0;',
        '}',
    ])
    return '\n'.join(lines)


def generate_add_setters():
    """Generate the optional property setters for the add command."""
    lines = []
    for flag, (setter, arg_type) in REMINDER_WRITE_OPS.items():
        if flag == "title":
            continue  # Title is already set via addReminderWithTitle:
        if arg_type == "string":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("{setter}"), opts[@"{flag}"]);')
            lines.append(f'    }}')
        elif arg_type == "bool":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        BOOL val = [opts[@"{flag}"] isEqualToString:@"true"];')
            lines.append(f'        ((void (*)(id, SEL, BOOL))objc_msgSend)(newRem, sel_registerName("{setter}"), val);')
            lines.append(f'    }}')
        elif arg_type == "uint":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        NSUInteger val = [opts[@"{flag}"] integerValue];')
            lines.append(f'        ((void (*)(id, SEL, NSUInteger))objc_msgSend)(newRem, sel_registerName("{setter}"), val);')
            lines.append(f'    }}')
        elif arg_type == "int":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        NSInteger val = [opts[@"{flag}"] integerValue];')
            lines.append(f'        ((void (*)(id, SEL, NSInteger))objc_msgSend)(newRem, sel_registerName("{setter}"), val);')
            lines.append(f'    }}')
        elif arg_type == "datecomps":
            lines.append(f'    if (opts[@"{flag}"]) {{')
            lines.append(f'        NSDateComponents *comps = stringToDateComps(opts[@"{flag}"]);')
            lines.append(f'        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("{setter}"), comps);')
            lines.append(f'    }}')
    return '\n'.join(lines)


def generate_test_command():
    return '''
static int cmdTest(id store) {
    int passed = 0, failed = 0;
    NSString *testListName = @"__remcli_test_list__";
    NSString *parentTitle = @"__remcli_test_parent__";
    NSString *childTitle = @"__remcli_test_child__";

    // Cleanup leftover test data
    id oldList = findList(store, testListName);
    if (oldList) {
        NSArray *oldRems = fetchReminders(store, oldList, YES);
        id cleanReq = ((id (*)(id, SEL, id))objc_msgSend)(
            [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);
        for (id oldRem in oldRems) {
            id ci = ((id (*)(id, SEL, id))objc_msgSend)(cleanReq, sel_registerName("updateReminder:"), oldRem);
            ((void (*)(id, SEL))objc_msgSend)(ci, sel_registerName("removeFromList"));
        }
        id listCI = ((id (*)(id, SEL, id))objc_msgSend)(cleanReq, sel_registerName("updateList:"), oldList);
        ((void (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("removeFromParent"));
        ((BOOL (*)(id, SEL, id*))objc_msgSend)(cleanReq, sel_registerName("saveSynchronouslyWithError:"), nil);
        fprintf(stderr, "Cleaned up leftover test data\\n");
    }

    // Test 1: cmdCreateList
    fprintf(stderr, "Test 1: cmdCreateList...\\n");
    { int r = cmdCreateList(store, testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; return 1; } }

    // Test 2: cmdLists (call actual command, verify it returns without error)
    fprintf(stderr, "Test 2: cmdLists...\\n");
    { int r = cmdLists(store); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 3: cmdAdd (create reminder with notes and priority)
    fprintf(stderr, "Test 3: cmdAdd...\\n");
    { int r = cmdAdd(store, parentTitle, testListName, @{@"notes": @"Test notes", @"priority": @"5"}); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 4: cmdGet (call actual command)
    fprintf(stderr, "Test 4: cmdGet...\\n");
    { int r = cmdGet(store, parentTitle, testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 5: cmdUpdate (change notes, priority, flagged)
    fprintf(stderr, "Test 5: cmdUpdate...\\n");
    { int r = cmdUpdate(store, parentTitle, testListName, @{@"notes": @"Updated", @"priority": @"1", @"flagged": @"1"}); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 6: Verify update
    fprintf(stderr, "Test 6: Verify update...\\n");
    {
        id rem = findReminder(store, parentTitle, testListName);
        NSString *notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
        NSUInteger pri = ((NSUInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("priority"));
        NSInteger flagged = ((NSInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("flagged"));
        if ([notes isEqualToString:@"Updated"] && pri == 1 && flagged == 1) { fprintf(stderr, "  PASS\\n"); passed++; }
        else { fprintf(stderr, "  FAIL (notes=%s pri=%lu flagged=%ld)\\n", [notes UTF8String], (unsigned long)pri, (long)flagged); failed++; }
    }

    // Test 7: cmdAddSubtask
    fprintf(stderr, "Test 7: cmdAddSubtask...\\n");
    { int r = cmdAddSubtask(store, parentTitle, childTitle, testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 8: cmdSubtasks (verify parent-child)
    fprintf(stderr, "Test 8: Verify parent-child...\\n");
    {
        id child = findReminder(store, childTitle, testListName);
        id parent = findReminder(store, parentTitle, testListName);
        id childPID = child ? ((id (*)(id, SEL))objc_msgSend)(child, sel_registerName("parentReminderID")) : nil;
        id parentOID = parent ? ((id (*)(id, SEL))objc_msgSend)(parent, sel_registerName("objectID")) : nil;
        if (childPID && parentOID && [objectIDToString(childPID) isEqualToString:objectIDToString(parentOID)]) {
            fprintf(stderr, "  PASS\\n"); passed++;
        } else { fprintf(stderr, "  FAIL\\n"); failed++; }
    }

    // Test 9: cmdAddTag
    fprintf(stderr, "Test 9: cmdAddTag...\\n");
    { int r = cmdAddTag(store, parentTitle, @"test-tag", testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 10: Verify tag in reminderToDict
    fprintf(stderr, "Test 10: Verify tag...\\n");
    {
        id rem = findReminder(store, parentTitle, testListName);
        NSDictionary *dict = reminderToDict(rem);
        NSArray *tags = dict[@"hashtags"];
        if (tags && [tags containsObject:@"test-tag"]) { fprintf(stderr, "  PASS\\n"); passed++; }
        else { fprintf(stderr, "  FAIL\\n"); failed++; }
    }

    // Test 11: cmdRemoveTag
    fprintf(stderr, "Test 11: cmdRemoveTag...\\n");
    { int r = cmdRemoveTag(store, parentTitle, @"test-tag", testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 12: cmdComplete (complete child)
    fprintf(stderr, "Test 12: cmdComplete...\\n");
    { int r = cmdComplete(store, childTitle, testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 13: cmdList (call actual command)
    fprintf(stderr, "Test 13: cmdList...\\n");
    { int r = cmdList(store, testListName, NO); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 14: Verify JSON shape from reminderToDict
    fprintf(stderr, "Test 14: JSON shape...\\n");
    {
        id rem = findReminder(store, parentTitle, testListName);
        NSDictionary *dict = reminderToDict(rem);
        BOOL hasTitle = dict[@"title"] != nil;
        BOOL hasNotes = dict[@"notes"] != nil;
        BOOL hasId = dict[@"id"] != nil;
        BOOL hasCompleted = dict[@"completed"] != nil;
        BOOL hasPriority = dict[@"priority"] != nil;
        BOOL hasCreatedAt = dict[@"createdAt"] != nil;
        BOOL hasModifiedAt = dict[@"modifiedAt"] != nil;
        if (hasTitle && hasNotes && hasId && hasCompleted && hasPriority && hasCreatedAt && hasModifiedAt) {
            fprintf(stderr, "  PASS\\n"); passed++;
        } else {
            fprintf(stderr, "  FAIL (missing fields: title=%d notes=%d id=%d completed=%d priority=%d created=%d modified=%d)\\n",
                hasTitle, hasNotes, hasId, hasCompleted, hasPriority, hasCreatedAt, hasModifiedAt); failed++;
        }
    }

    // Test 15: cmdUpdate --title (rename)
    fprintf(stderr, "Test 15: Rename via update...\\n");
    {
        NSString *renamedTitle = @"__remcli_test_renamed__";
        int r = cmdUpdate(store, parentTitle, testListName, @{@"title": renamedTitle});
        if (r == 0) {
            id found = findReminder(store, renamedTitle, testListName);
            if (found) {
                // Rename back
                cmdUpdate(store, renamedTitle, testListName, @{@"title": parentTitle});
                fprintf(stderr, "  PASS\\n"); passed++;
            } else { fprintf(stderr, "  FAIL (not found after rename)\\n"); failed++; }
        } else { fprintf(stderr, "  FAIL\\n"); failed++; }
    }

    // Test 16: cmdRenameList
    fprintf(stderr, "Test 16: cmdRenameList...\\n");
    {
        NSString *renamedList = @"__remcli_test_list_renamed__";
        int r = cmdRenameList(store, testListName, renamedList);
        if (r == 0) {
            id found = findList(store, renamedList);
            if (found) {
                // Rename back
                cmdRenameList(store, renamedList, testListName);
                fprintf(stderr, "  PASS\\n"); passed++;
            } else { fprintf(stderr, "  FAIL (not found after rename)\\n"); failed++; }
        } else { fprintf(stderr, "  FAIL\\n"); failed++; }
    }

    // Test 17: cmdSubtasks (call actual command)
    fprintf(stderr, "Test 17: cmdSubtasks...\\n");
    { int r = cmdSubtasks(store, parentTitle, testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 18: Error path - find non-existent reminder
    fprintf(stderr, "Test 18: Error path (not found)...\\n");
    {
        id notFound = findReminder(store, @"__nonexistent_reminder_999__", testListName);
        if (!notFound) { fprintf(stderr, "  PASS\\n"); passed++; }
        else { fprintf(stderr, "  FAIL (should be nil)\\n"); failed++; }
    }

    // Test 19: Error path - find non-existent list
    fprintf(stderr, "Test 19: Error path (list not found)...\\n");
    {
        id notFound = findList(store, @"__nonexistent_list_999__");
        if (!notFound) { fprintf(stderr, "  PASS\\n"); passed++; }
        else { fprintf(stderr, "  FAIL (should be nil)\\n"); failed++; }
    }

    // Cleanup
    // Test 20: cmdDelete child
    fprintf(stderr, "Test 20: cmdDelete child...\\n");
    { int r = cmdDelete(store, childTitle, testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 21: cmdDelete parent
    fprintf(stderr, "Test 21: cmdDelete parent...\\n");
    { int r = cmdDelete(store, parentTitle, testListName); if (r==0) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    // Test 22: cmdDeleteList
    fprintf(stderr, "Test 22: cmdDeleteList...\\n");
    { int r = cmdDeleteList(store, testListName); if (r==0) {
        id gone = findList(store, testListName);
        if (!gone) { fprintf(stderr, "  PASS\\n"); passed++; } else { fprintf(stderr, "  FAIL (still exists)\\n"); failed++; }
    } else { fprintf(stderr, "  FAIL\\n"); failed++; } }

    fprintf(stderr, "\\nResults: %d passed, %d failed\\n", passed, failed);
    return failed > 0 ? 1 : 0;
}
'''


def generate_delete_command():
    return '''
static int cmdDelete(id store, NSString *title, NSString *listName) {
    id rem = findReminder(store, title, listName);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("removeFromList"));

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"title": title, @"deleted": @YES});
    return 0;
}
'''


def generate_complete_command():
    return '''
static int cmdComplete(id store, NSString *title, NSString *listName) {
    id rem = findReminder(store, title, listName);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("setCompleted:"), YES);

    NSError *error = nil;
    BOOL saved = ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"title": title, @"completed": @YES});
    return 0;
}
'''


def generate_usage():
    write_flags = ' '.join(f'[--{f} <value>]' for f in REMINDER_WRITE_OPS.keys())
    special_flags = ' '.join(f'[--{f}]' for f in SPECIAL_WRITE_OPS.keys())

    return f'''
static void usage(void) {{
    fprintf(stderr, "Usage:\\n");
    fprintf(stderr, "  reminders-cli lists\\n");
    fprintf(stderr, "  reminders-cli list <name> [--include-completed]\\n");
    fprintf(stderr, "  reminders-cli get <title> [--list <name>]\\n");
    fprintf(stderr, "  reminders-cli subtasks <title> [--list <name>]\\n");
    fprintf(stderr, "  reminders-cli add <title> [--list <name>] {write_flags}\\n");
    fprintf(stderr, "  reminders-cli update <title> [--list <name>] {write_flags} {special_flags}\\n");
    fprintf(stderr, "  reminders-cli complete <title> [--list <name>]\\n");
    fprintf(stderr, "  reminders-cli delete <title> [--list <name>]\\n");
    fprintf(stderr, "  reminders-cli add-tag <title> <tag-name> [--list <name>]\\n");
    fprintf(stderr, "  reminders-cli remove-tag <title> <tag-name> [--list <name>]\\n");
    fprintf(stderr, "  reminders-cli list-sections <list-name>\\n");
    fprintf(stderr, "  reminders-cli create-section <list-name> <section-name>\\n");
    fprintf(stderr, "  reminders-cli create-list <name>\\n");
    fprintf(stderr, "  reminders-cli rename-list <old-name> <new-name>\\n");
    fprintf(stderr, "  reminders-cli delete-list <name>\\n");
    fprintf(stderr, "\\n  Composed (convenience):\\n");
    fprintf(stderr, "  reminders-cli add-subtask <parent> <child> [--list <name>]\\n");
    fprintf(stderr, "\\n  Testing:\\n");
    fprintf(stderr, "  reminders-cli test\\n");
}}
'''


def generate_main():
    """Generate main() with argument parsing."""
    # Build the list of all possible flags
    all_flags = set()
    all_flags.add("list")
    all_flags.add("include-completed")
    for f in REMINDER_WRITE_OPS.keys():
        all_flags.add(f)
    for f in SPECIAL_WRITE_OPS.keys():
        all_flags.add(f)

    return '''
int main(int argc, const char *argv[]) {
    @autoreleasepool {
        if (argc < 2) { usage(); return 1; }

        loadFramework();

        NSString *command = [NSString stringWithUTF8String:argv[1]];

        // Parse arguments
        NSMutableArray *positional = [NSMutableArray array];
        NSMutableDictionary *opts = [NSMutableDictionary dictionary];
        BOOL includeCompleted = NO;

        for (int i = 2; i < argc; i++) {
            NSString *arg = [NSString stringWithUTF8String:argv[i]];
            if ([arg hasPrefix:@"--"]) {
                NSString *flag = [arg substringFromIndex:2];
                if ([flag isEqualToString:@"include-completed"] ||
                    [flag isEqualToString:@"remove-parent"] ||
                    [flag isEqualToString:@"remove-from-list"]) {
                    if ([flag isEqualToString:@"include-completed"]) includeCompleted = YES;
                    opts[flag] = @"true";
                } else if (i + 1 < argc) {
                    opts[flag] = [NSString stringWithUTF8String:argv[++i]];
                }
            } else {
                [positional addObject:arg];
            }
        }

        NSString *listName = opts[@"list"];
        id store = getStore();

        if ([command isEqualToString:@"lists"]) {
            return cmdLists(store);

        } else if ([command isEqualToString:@"list"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: list name required\\n"); usage(); return 1; }
            return cmdList(store, positional[0], includeCompleted);

        } else if ([command isEqualToString:@"get"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: title required\\n"); usage(); return 1; }
            return cmdGet(store, positional[0], listName);

        } else if ([command isEqualToString:@"subtasks"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: title required\\n"); usage(); return 1; }
            return cmdSubtasks(store, positional[0], listName);

        } else if ([command isEqualToString:@"add"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: title required\\n"); usage(); return 1; }
            return cmdAdd(store, positional[0], listName, opts);

        } else if ([command isEqualToString:@"add-subtask"]) {
            if (positional.count < 2) { fprintf(stderr, "Error: parent and child titles required\\n"); usage(); return 1; }
            return cmdAddSubtask(store, positional[0], positional[1], listName);

        } else if ([command isEqualToString:@"update"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: title required\\n"); usage(); return 1; }
            return cmdUpdate(store, positional[0], listName, opts);

        } else if ([command isEqualToString:@"complete"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: title required\\n"); usage(); return 1; }
            return cmdComplete(store, positional[0], listName);

        } else if ([command isEqualToString:@"delete"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: title required\\n"); usage(); return 1; }
            return cmdDelete(store, positional[0], listName);

        } else if ([command isEqualToString:@"add-tag"]) {
            if (positional.count < 2) { fprintf(stderr, "Error: title and tag name required\\n"); usage(); return 1; }
            return cmdAddTag(store, positional[0], positional[1], listName);

        } else if ([command isEqualToString:@"remove-tag"]) {
            if (positional.count < 2) { fprintf(stderr, "Error: title and tag name required\\n"); usage(); return 1; }
            return cmdRemoveTag(store, positional[0], positional[1], listName);

        } else if ([command isEqualToString:@"list-sections"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: list name required\\n"); usage(); return 1; }
            return cmdListSections(store, positional[0]);

        } else if ([command isEqualToString:@"create-section"]) {
            if (positional.count < 2) { fprintf(stderr, "Error: list name and section name required\\n"); usage(); return 1; }
            return cmdCreateSection(store, positional[0], positional[1]);

        } else if ([command isEqualToString:@"create-list"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: list name required\\n"); usage(); return 1; }
            return cmdCreateList(store, positional[0]);

        } else if ([command isEqualToString:@"rename-list"]) {
            if (positional.count < 2) { fprintf(stderr, "Error: old and new names required\\n"); usage(); return 1; }
            return cmdRenameList(store, positional[0], positional[1]);

        } else if ([command isEqualToString:@"delete-list"]) {
            if (positional.count < 1) { fprintf(stderr, "Error: list name required\\n"); usage(); return 1; }
            return cmdDeleteList(store, positional[0]);

        } else if ([command isEqualToString:@"test"]) {
            return cmdTest(store);

        } else {
            fprintf(stderr, "Unknown command: %s\\n", [command UTF8String]);
            usage();
            return 1;
        }
    }
}
'''


def main():
    output = []
    output.append(generate_header())
    output.append('')
    output.append('// --- Reminder Serialization (generated from REMINDER_READ_PROPS) ---')
    output.append('')
    output.append(generate_reminder_to_dict())
    output.append('')
    output.append(generate_commands())
    output.append('')
    output.append('// --- Update Command (generated from REMINDER_WRITE_OPS) ---')
    output.append('')
    output.append(generate_update_command())
    output.append('')
    output.append(generate_complete_command())
    output.append('')
    output.append(generate_delete_command())
    output.append('')
    output.append('// --- Tests ---')
    output.append(generate_test_command())
    output.append('')
    output.append('// --- Usage ---')
    output.append(generate_usage())
    output.append('')
    output.append('// --- Main ---')
    output.append(generate_main())

    print('\n'.join(output))


if __name__ == '__main__':
    main()
