// AUTO-GENERATED by generate-cli.py — do not edit manually

#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <objc/message.h>
#include <mach-o/dyld.h>
#include <unistd.h>
#include <sys/wait.h>
#include <spawn.h>
#include <fcntl.h>

// --- Framework Loading ---

static Class REMStoreClass;
static Class REMSaveRequestClass;
static Class REMListSectionCIClass;

static void loadFramework(void) {
    [[NSBundle bundleWithPath:@"/System/Library/PrivateFrameworks/ReminderKit.framework"] load];
    REMStoreClass = NSClassFromString(@"REMStore");
    REMSaveRequestClass = NSClassFromString(@"REMSaveRequest");
    REMListSectionCIClass = NSClassFromString(@"REMListSectionChangeItem");
}

static id getStore(void) {
    return ((id (*)(id, SEL, BOOL))objc_msgSend)(
        [REMStoreClass alloc], sel_registerName("initUserInteractive:"), YES);
}

// --- Forward Declarations ---

static id findListByObjectID(id store, id targetObjID);
static void reparentChangeItemAfter(id store, id saveReq, id listCI, id childCI, NSString *parentID, id afterSiblingCI);
static void reparentChangeItemBefore(id store, id saveReq, id listCI, id childCI, NSString *parentID, id beforeSiblingCI);

// --- Helpers ---

static void errorExit(NSString *msg) {
    fprintf(stderr, "Error: %s\n", [msg UTF8String]);
    exit(1);
}

static BOOL parseBoolString(NSString *str) {
    NSString *lower = [str lowercaseString];
    return [lower isEqualToString:@"true"] || [lower isEqualToString:@"1"] || [lower isEqualToString:@"yes"];
}

static NSString *objectIDToString(id objID) {
    if (!objID) return nil;
    return [objID description];
}

// --- ID Output Mode (omit-when-default, field projection, full mode) ---
// Populated from CLI flags in main(). Shared by reminderToDict + helpers.
static BOOL gOutputFull = NO;               // --full
static NSArray *gOutputFields = nil;        // --fields id,title,notes,...
static BOOL gOutputLegacyID = NO;           // batch results keep old id format

// NSManagedObjectID description looks like:
//   "🎅~<x-apple-reminderkit://REMCDReminder/706D8583-A718-4644-9056-E79D9C8E9625>"
// Extract the canonical x-callback-url form (no emoji, no angle brackets).
static NSString *objectIDToURI(id objID) {
    if (!objID) return nil;
    NSString *desc = [objID description];
    if (!desc) return nil;
    // Find the first '<' and the matching '>' at the end.
    NSRange lt = [desc rangeOfString:@"<"];
    NSRange gt = [desc rangeOfString:@">" options:NSBackwardsSearch];
    if (lt.location != NSNotFound && gt.location != NSNotFound && gt.location > lt.location) {
        return [desc substringWithRange:NSMakeRange(lt.location + 1, gt.location - lt.location - 1)];
    }
    // Fallback: if the string already starts with the scheme, return as-is.
    if ([desc hasPrefix:@"x-apple-reminderkit://"]) return desc;
    return desc;
}

// Extract the bare UUID (last path component) from an NSManagedObjectID.
// Returns nil if no UUID-shaped token is found.
static NSString *objectIDToUUID(id objID) {
    if (!objID) return nil;
    NSString *uri = objectIDToURI(objID);
    if (!uri) return nil;
    NSArray *parts = [uri componentsSeparatedByString:@"/"];
    if (parts.count == 0) return nil;
    NSString *tail = [parts lastObject];
    // Strip any stray trailing '>' just in case.
    if ([tail hasSuffix:@">"]) tail = [tail substringToIndex:tail.length - 1];
    // Validate UUID shape (36 chars with dashes).
    if (tail.length == 36 && [tail characterAtIndex:8] == '-') return [tail uppercaseString];
    return nil;
}

// Build the full legacy id string (with emoji prefix) from an NSManagedObjectID.
// This is the exact byte-for-byte representation scripts using pre-v2 output
// would see. Only used in --full mode for the "id" field.
static NSString *objectIDToLegacyString(id objID) {
    return objectIDToString(objID);
}

// Accept either a bare UUID or any form that contains one ("706D...", the full
// emoji-URL wrapped form, the naked x-apple-reminderkit:// URL, etc.). Returns
// the uppercased bare UUID, or nil if the input doesn't look like one.
static NSString *normalizeIDInput(NSString *input) {
    if (!input || input.length == 0) return nil;
    // If the whole input is already a UUID, short-circuit.
    if (input.length == 36 && [input characterAtIndex:8] == '-') {
        return [input uppercaseString];
    }
    // Otherwise scan for a UUID-shaped token (36 chars, dash positions 8/13/18/23).
    NSCharacterSet *hex = [NSCharacterSet characterSetWithCharactersInString:@"0123456789abcdefABCDEF-"];
    NSUInteger n = input.length;
    for (NSUInteger i = 0; i + 36 <= n; i++) {
        BOOL ok = YES;
        for (NSUInteger j = 0; j < 36; j++) {
            unichar c = [input characterAtIndex:i + j];
            if (![hex characterIsMember:c]) { ok = NO; break; }
            if ((j == 8 || j == 13 || j == 18 || j == 23) && c != '-') { ok = NO; break; }
            if (j != 8 && j != 13 && j != 18 && j != 23 && c == '-') { ok = NO; break; }
        }
        if (ok) return [[input substringWithRange:NSMakeRange(i, 36)] uppercaseString];
    }
    return nil;
}

// Add a key to a shaped dict's field order (used when callers add new keys
// after shaping, e.g. subtasks, listName). No-op if not a shaped dict.
static void addFieldIfRequested(NSMutableDictionary *dict, NSString *key, id value) {
    if (!value) return;
    if (gOutputFields && gOutputFields.count > 0) {
        if (![gOutputFields containsObject:key]) return;  // not requested, drop
        dict[key] = value;
        NSMutableArray *order = dict[@"__fieldOrder__"];
        if ([order isKindOfClass:[NSMutableArray class]] && ![order containsObject:key]) {
            [order addObject:key];
        }
        return;
    }
    dict[key] = value;
}

// --- Field projection helper ---
// Apply gOutputFields / gOutputFull / OMIT_WHEN_DEFAULT to a fully-populated dict.
// When gOutputFields is set we return an ordered dict containing only the requested
// keys (preserving user-specified order, values taken from src).
// When gOutputFull is NO and gOutputFields is nil, we apply the omit-when-default rules.
// Omit-when-default rules (only relevant when --full is NOT set):
//   allDay=false, completed=false, flagged=0, isOverdue=false,
//   isRecurrent=false, priority=0, hashtags=[]
static id applyOutputShape(NSDictionary *src) {
    // --fields takes precedence over --full
    if (gOutputFields && gOutputFields.count > 0) {
        // Preserve order via a plain NSMutableDictionary plus a sibling order array
        // that printJSON's sortedKeys would otherwise destroy. We therefore use
        // NSJSONWritingSortedKeys=NO and build an NSMutableDictionary that the
        // printer renders in insertion order. See printJSON below.
        NSMutableDictionary *out = [NSMutableDictionary dictionary];
        NSMutableArray *order = [NSMutableArray array];
        for (NSString *field in gOutputFields) {
            id v = src[field];
            if (v) {
                out[field] = v;
                [order addObject:field];
            }
        }
        out[@"__fieldOrder__"] = order;  // printer reads and strips this
        return out;
    }
    if (gOutputFull) return src;  // all fields including defaults

    // Default: omit-when-default
    NSMutableDictionary *out = [src mutableCopy];
    if ([out[@"allDay"] isKindOfClass:[NSNumber class]] && ![out[@"allDay"] boolValue]) [out removeObjectForKey:@"allDay"];
    if ([out[@"completed"] isKindOfClass:[NSNumber class]] && ![out[@"completed"] boolValue]) [out removeObjectForKey:@"completed"];
    if ([out[@"isOverdue"] isKindOfClass:[NSNumber class]] && ![out[@"isOverdue"] boolValue]) [out removeObjectForKey:@"isOverdue"];
    if ([out[@"isRecurrent"] isKindOfClass:[NSNumber class]] && ![out[@"isRecurrent"] boolValue]) [out removeObjectForKey:@"isRecurrent"];
    if ([out[@"priority"] isKindOfClass:[NSNumber class]] && [out[@"priority"] integerValue] == 0) [out removeObjectForKey:@"priority"];
    if ([out[@"flagged"] isKindOfClass:[NSNumber class]] && [out[@"flagged"] integerValue] == 0) [out removeObjectForKey:@"flagged"];
    if ([out[@"hashtags"] isKindOfClass:[NSArray class]] && [(NSArray *)out[@"hashtags"] count] == 0) [out removeObjectForKey:@"hashtags"];
    return out;
}

static NSString *dateToISO(NSDate *date) {
    if (!date) return nil;
    NSISO8601DateFormatter *fmt = [[NSISO8601DateFormatter alloc] init];
    return [fmt stringFromDate:date];
}

static NSString *dateCompsToString(NSDateComponents *comps) {
    if (!comps) return nil;
    NSCalendar *cal = [NSCalendar currentCalendar];
    NSDate *date = [cal dateFromComponents:comps];
    if (date) return dateToISO(date);
    // Fallback: manual formatting
    return [NSString stringWithFormat:@"%04ld-%02ld-%02ld",
        (long)[comps year], (long)[comps month], (long)[comps day]];
}

static NSDateComponents *stringToDateComps(NSString *str) {
    // Parse ISO date string like "2026-03-15" or "2026-03-15T10:00:00"
    NSDateComponents *comps = [[NSDateComponents alloc] init];
    NSArray *parts = [str componentsSeparatedByString:@"T"];
    NSArray *dateParts = [parts[0] componentsSeparatedByString:@"-"];
    if (dateParts.count >= 3) {
        comps.year = [dateParts[0] integerValue];
        comps.month = [dateParts[1] integerValue];
        comps.day = [dateParts[2] integerValue];
    }
    if (parts.count > 1) {
        NSArray *timeParts = [parts[1] componentsSeparatedByString:@":"];
        if (timeParts.count >= 2) {
            comps.hour = [timeParts[0] integerValue];
            comps.minute = [timeParts[1] integerValue];
        }
    }
    return comps;
}

static NSString *normalizeQuotes(NSString *str) {
    if (!str) return nil;
    NSString *result = [str stringByReplacingOccurrencesOfString:@"\u2018" withString:@"'"];
    result = [result stringByReplacingOccurrencesOfString:@"\u2019" withString:@"'"];
    return result;
}

// Strip any internal "__fieldOrder__" markers from a JSON-ready structure.
// Returns a new object tree. Used by printJSON before serialisation.
static id stripFieldOrderMarkers(id obj) {
    if ([obj isKindOfClass:[NSDictionary class]]) {
        NSDictionary *src = obj;
        NSMutableDictionary *dst = [NSMutableDictionary dictionary];
        for (NSString *k in src) {
            if ([k isEqualToString:@"__fieldOrder__"]) continue;
            dst[k] = stripFieldOrderMarkers(src[k]);
        }
        return dst;
    }
    if ([obj isKindOfClass:[NSArray class]]) {
        NSMutableArray *dst = [NSMutableArray array];
        for (id e in obj) [dst addObject:stripFieldOrderMarkers(e)];
        return dst;
    }
    return obj;
}

// Serialize JSON manually when any top-level or nested dict has a
// __fieldOrder__ marker, so we can preserve insertion order. Otherwise
// fall back to NSJSONSerialization (sorted keys for stability).
static NSString *jsonIndent(NSUInteger lvl) {
    NSMutableString *s = [NSMutableString string];
    for (NSUInteger i = 0; i < lvl; i++) [s appendString:@"  "];
    return s;
}

// Return the JSON-escaped string body (INCLUDING surrounding quotes).
// Example: jsonEscapeQuoted(@"he\"llo") -> "\"he\\\"llo\""
static NSString *jsonEscapeQuoted(NSString *s) {
    NSError *e = nil;
    NSData *d = [NSJSONSerialization dataWithJSONObject:@[s] options:0 error:&e];
    if (!d) return @"\"\"";
    NSString *full = [[NSString alloc] initWithData:d encoding:NSUTF8StringEncoding];
    // full looks like ["..."], strip the outer brackets only
    if (full.length >= 4) return [full substringWithRange:NSMakeRange(1, full.length - 2)];
    return @"\"\"";
}

static void jsonWriteValue(NSMutableString *out, id v, NSUInteger lvl, BOOL hasOrder);

static void jsonWriteDict(NSMutableString *out, NSDictionary *d, NSUInteger lvl, BOOL hasOrder) {
    NSArray *keys;
    NSArray *orderMarker = d[@"__fieldOrder__"];
    if ([orderMarker isKindOfClass:[NSArray class]]) {
        keys = orderMarker;
    } else {
        // Sort keys for stability, matching NSJSONWritingSortedKeys.
        keys = [[d allKeys] sortedArrayUsingSelector:@selector(compare:)];
    }
    if (keys.count == 0) { [out appendString:@"{\n\n"]; [out appendString:jsonIndent(lvl)]; [out appendString:@"}"]; return; }
    [out appendString:@"{\n"];
    NSUInteger idx = 0;
    for (NSString *k in keys) {
        if ([k isEqualToString:@"__fieldOrder__"]) continue;
        id v = d[k];
        if (!v) continue;
        [out appendString:jsonIndent(lvl + 1)];
        [out appendString:jsonEscapeQuoted(k)];
        [out appendString:@" : "];
        jsonWriteValue(out, v, lvl + 1, hasOrder);
        // We don't easily know if there's a next key; append comma+newline unconditionally
        // and strip the trailing ,\n below.
        [out appendString:@",\n"];
        idx++;
    }
    // Strip trailing ",\n"
    if (idx > 0 && [out hasSuffix:@",\n"]) [out deleteCharactersInRange:NSMakeRange(out.length - 2, 2)];
    [out appendString:@"\n"];
    [out appendString:jsonIndent(lvl)];
    [out appendString:@"}"];
}

static void jsonWriteArray(NSMutableString *out, NSArray *a, NSUInteger lvl, BOOL hasOrder) {
    if (a.count == 0) { [out appendString:@"[]"]; return; }
    [out appendString:@"[\n"];
    for (NSUInteger i = 0; i < a.count; i++) {
        [out appendString:jsonIndent(lvl + 1)];
        jsonWriteValue(out, a[i], lvl + 1, hasOrder);
        if (i + 1 < a.count) [out appendString:@","];
        [out appendString:@"\n"];
    }
    [out appendString:jsonIndent(lvl)];
    [out appendString:@"]"];
}

static void jsonWriteValue(NSMutableString *out, id v, NSUInteger lvl, BOOL hasOrder) {
    if ([v isKindOfClass:[NSDictionary class]]) { jsonWriteDict(out, v, lvl, hasOrder); return; }
    if ([v isKindOfClass:[NSArray class]]) { jsonWriteArray(out, v, lvl, hasOrder); return; }
    if ([v isKindOfClass:[NSString class]]) {
        [out appendString:jsonEscapeQuoted(v)];
        return;
    }
    if ([v isKindOfClass:[NSNumber class]]) {
        NSNumber *n = v;
        // Objective-C: @YES/@NO are NSNumbers; detect via objCType.
        const char *t = [n objCType];
        if (t[0] == 'c' || t[0] == 'B') { [out appendString:[n boolValue] ? @"true" : @"false"]; return; }
        [out appendString:[n stringValue]];
        return;
    }
    if (v == [NSNull null] || !v) { [out appendString:@"null"]; return; }
    // Fallback: serialize via NSJSONSerialization in a wrapper array.
    NSError *e = nil;
    NSData *d = [NSJSONSerialization dataWithJSONObject:@[v] options:0 error:&e];
    if (d) {
        NSString *s = [[NSString alloc] initWithData:d encoding:NSUTF8StringEncoding];
        if (s.length >= 2) { [out appendString:[s substringWithRange:NSMakeRange(1, s.length - 2)]]; return; }
    }
    [out appendString:@"null"];
}

// Recursively walk and set hasOrder=YES if any dict has __fieldOrder__.
static BOOL hasFieldOrderMarker(id obj) {
    if ([obj isKindOfClass:[NSDictionary class]]) {
        if (((NSDictionary *)obj)[@"__fieldOrder__"]) return YES;
        for (id v in [(NSDictionary *)obj allValues]) {
            if (hasFieldOrderMarker(v)) return YES;
        }
    } else if ([obj isKindOfClass:[NSArray class]]) {
        for (id v in (NSArray *)obj) if (hasFieldOrderMarker(v)) return YES;
    }
    return NO;
}

static void printJSON(id obj) {
    if (hasFieldOrderMarker(obj)) {
        NSMutableString *out = [NSMutableString string];
        jsonWriteValue(out, obj, 0, YES);
        printf("%s\n", [out UTF8String]);
        return;
    }
    NSError *error = nil;
    NSData *data = [NSJSONSerialization dataWithJSONObject:obj
        options:NSJSONWritingPrettyPrinted | NSJSONWritingSortedKeys error:&error];
    if (error) errorExit([error localizedDescription]);
    printf("%s\n", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding].UTF8String);
}

// --- List Helpers ---

static NSArray *fetchLists(id store) {
    NSError *error = nil;
    NSArray *lists = ((id (*)(id, SEL, id*))objc_msgSend)(
        store, sel_registerName("fetchEligibleDefaultListsWithError:"), &error);
    if (error) {
        if ([[error domain] isEqualToString:@"NSCocoaErrorDomain"] && [error code] == 4097) {
            fprintf(stderr, "Error: Reminders access denied.\n\n");
            fprintf(stderr, "Your terminal app needs permission to access Reminders.\n\n");
            fprintf(stderr, "1. Grant permission (triggers macOS prompt):\n");
            fprintf(stderr, "   osascript -e 'tell application \"Reminders\" to get name of every list'\n\n");
            fprintf(stderr, "2. If previously denied, reset first, then re-run step 1:\n");
            fprintf(stderr, "   tccutil reset Reminders <bundle-id>\n\n");
            fprintf(stderr, "   Find your terminal's bundle ID:\n");
            fprintf(stderr, "   osascript -e 'id of app \"iTerm\"'  (replace iTerm with your terminal app name)\n\n");
            fprintf(stderr, "3. Then retry: reminderkit lists\n");
            exit(1);
        }
        errorExit([NSString stringWithFormat:@"Failed to fetch lists: %@", error]);
    }
    return lists;
}

static id findList(id store, NSString *name) {
    NSArray *lists = fetchLists(store);
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *listName = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        if ([listName isEqualToString:name]) return list;
    }
    // Normalized fallback: retry with curly quotes normalized to straight quotes
    NSString *normalizedName = normalizeQuotes(name);
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *listName = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        if ([normalizeQuotes(listName) isEqualToString:normalizedName]) return list;
    }
    return nil;
}

static NSArray *fetchReminders(id store, id list, BOOL includeCompleted) {
    id listObjID = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("objectID"));
    NSError *error = nil;
    NSArray *all = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listObjID], &error);
    if (error) errorExit([NSString stringWithFormat:@"Failed to fetch reminders: %@", error]);
    if (includeCompleted) return all;
    NSMutableArray *incomplete = [NSMutableArray array];
    for (id rem in all) {
        BOOL done = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isCompleted"));
        if (!done) [incomplete addObject:rem];
    }
    return incomplete;
}

static id findReminder(id store, NSString *title, NSString *listName) {
    NSArray *lists;
    if (listName) {
        id list = findList(store, listName);
        if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
        lists = @[list];
    } else {
        lists = fetchLists(store);
    }
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, YES);
        for (id rem in rems) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            if ([t isEqualToString:title]) return rem;
        }
    }
    // Normalized fallback: retry with curly quotes normalized to straight quotes
    NSString *normalizedTitle = normalizeQuotes(title);
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, YES);
        for (id rem in rems) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            if ([normalizeQuotes(t) isEqualToString:normalizedTitle]) return rem;
        }
    }
    return nil;
}

static NSString *normalizeURL(NSString *url) {
    // Strip trailing slash for comparison
    while ([url hasSuffix:@"/"]) {
        url = [url substringToIndex:url.length - 1];
    }
    return [url lowercaseString];
}

static NSArray *findReminders(id store, NSString *title, NSString *listName) {
    NSArray *lists;
    if (listName) {
        id list = findList(store, listName);
        if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
        lists = @[list];
    } else {
        lists = fetchLists(store);
    }
    NSMutableArray *results = [NSMutableArray array];
    NSString *normalizedTitle = normalizeQuotes(title);
    NSString *lowerTitle = [normalizedTitle lowercaseString];
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, NO);
        for (id rem in rems) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            if (!t) continue;
            NSString *lowerT = [[normalizeQuotes(t) lowercaseString] copy];
            if ([lowerT rangeOfString:lowerTitle].location != NSNotFound) {
                [results addObject:rem];
            }
        }
    }
    return results;
}

static NSArray *findRemindersByURL(id store, NSString *url, NSString *listName) {
    NSArray *lists;
    if (listName) {
        id list = findList(store, listName);
        if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
        lists = @[list];
    } else {
        lists = fetchLists(store);
    }
    NSMutableArray *results = [NSMutableArray array];
    NSString *normalizedSearch = normalizeURL(url);
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, NO);
        for (id rem in rems) {
            @try {
                id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                if (!attCtx) continue;
                NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                if (urlAtts.count == 0) continue;
                NSURL *attUrl = ((id (*)(id, SEL))objc_msgSend)(urlAtts[0], sel_registerName("url"));
                if (!attUrl) continue;
                NSString *normalizedAtt = normalizeURL([attUrl absoluteString]);
                if ([normalizedAtt isEqualToString:normalizedSearch]) {
                    [results addObject:rem];
                }
            } @catch (NSException *e) {}
        }
    }
    return results;
}

static id findReminderByID(id store, NSString *idString) {
    if (!idString) return nil;
    // Accept EITHER a bare UUID or any form that contains one (emoji-URL
    // wrapped, naked scheme URL, etc.). We normalize both sides.
    NSString *normalizedInput = normalizeIDInput(idString);
    NSArray *lists = fetchLists(store);
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, YES);
        for (id rem in rems) {
            id objID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
            NSString *uuid = objectIDToUUID(objID);
            if (normalizedInput && uuid && [uuid isEqualToString:normalizedInput]) return rem;
            // Fallback for legacy exact-match (emoji-URL form or scheme URL)
            NSString *idStr = objectIDToString(objID);
            if (idStr && [idStr isEqualToString:idString]) return rem;
        }
    }
    return nil;
}

static id requireUniqueReminder(id store, NSString *title, NSString *listName) {
    NSArray *matches = findReminders(store, title, listName);
    if (matches.count == 0) {
        errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);
    }
    if (matches.count > 1) {
        NSMutableString *msg = [NSMutableString stringWithFormat:@"Multiple reminders match '%@'. Use --id to specify:\n", title];
        for (id rem in matches) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            id objID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
            NSString *idStr = objectIDToString(objID);
            [msg appendFormat:@"  - \"%@\" (id: %@)\n", t, idStr];
        }
        errorExit(msg);
    }
    return matches[0];
}


// --- Reminder Serialization (generated from REMINDER_READ_PROPS) ---

static NSMutableDictionary *reminderToDict(id rem) {
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];

    @try {
        NSString *val_title = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
        if (val_title) dict[@"title"] = val_title;
    } @catch (NSException *e) {}

    @try {
        NSString *val_notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
        if (val_notes) dict[@"notes"] = val_notes;
    } @catch (NSException *e) {}

    @try {
        BOOL val_completed = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isCompleted"));
        dict[@"completed"] = @(val_completed);
    } @catch (NSException *e) {}

    @try {
        NSUInteger val_priority = ((NSUInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("priority"));
        dict[@"priority"] = @(val_priority);
    } @catch (NSException *e) {}

    @try {
        NSInteger val_flagged = ((NSInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("flagged"));
        dict[@"flagged"] = @(val_flagged);
    } @catch (NSException *e) {}

    @try {
        BOOL val_allDay = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("allDay"));
        dict[@"allDay"] = @(val_allDay);
    } @catch (NSException *e) {}

    @try {
        BOOL val_isOverdue = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isOverdue"));
        dict[@"isOverdue"] = @(val_isOverdue);
    } @catch (NSException *e) {}

    @try {
        BOOL val_isRecurrent = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isRecurrent"));
        dict[@"isRecurrent"] = @(val_isRecurrent);
    } @catch (NSException *e) {}

    @try {
        id val_id = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
        if (val_id) {
            if (gOutputFull) {
                dict[@"id"] = objectIDToLegacyString(val_id);
                NSString *_uuid = objectIDToUUID(val_id);
                if (_uuid) dict[@"uuid"] = _uuid;
            } else {
                NSString *_uuid = objectIDToUUID(val_id);
                dict[@"id"] = _uuid ?: objectIDToString(val_id);
                NSString *_uri = objectIDToURI(val_id);
                if (_uri) dict[@"uri"] = _uri;
            }
        }
    } @catch (NSException *e) {}

    @try {
        id val_listId = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
        if (val_listId) {
            if (gOutputFull) {
                dict[@"listID"] = objectIDToLegacyString(val_listId);
            } else {
                NSString *_uuid = objectIDToUUID(val_listId);
                dict[@"listId"] = _uuid ?: objectIDToString(val_listId);
                NSString *_uri = objectIDToURI(val_listId);
                if (_uri) dict[@"listUri"] = _uri;
            }
        }
    } @catch (NSException *e) {}

    @try {
        id val_parentId = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("parentReminderID"));
        if (val_parentId) {
            if (gOutputFull) {
                dict[@"parentID"] = objectIDToLegacyString(val_parentId);
            } else {
                NSString *_uuid = objectIDToUUID(val_parentId);
                dict[@"parentId"] = _uuid ?: objectIDToString(val_parentId);
                NSString *_uri = objectIDToURI(val_parentId);
                if (_uri) dict[@"parentUri"] = _uri;
            }
        }
    } @catch (NSException *e) {}

    @try {
        NSDateComponents *val_dueDate = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("dueDateComponents"));
        if (val_dueDate) dict[@"dueDate"] = dateCompsToString(val_dueDate);
    } @catch (NSException *e) {}

    @try {
        NSDateComponents *val_startDate = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("startDateComponents"));
        if (val_startDate) dict[@"startDate"] = dateCompsToString(val_startDate);
    } @catch (NSException *e) {}

    @try {
        NSDate *val_createdAt = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("creationDate"));
        if (val_createdAt) dict[@"createdAt"] = dateToISO(val_createdAt);
    } @catch (NSException *e) {}

    @try {
        NSDate *val_modifiedAt = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("lastModifiedDate"));
        if (val_modifiedAt) dict[@"modifiedAt"] = dateToISO(val_modifiedAt);
    } @catch (NSException *e) {}

    @try {
        NSDate *val_completedAt = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("completionDate"));
        if (val_completedAt) dict[@"completedAt"] = dateToISO(val_completedAt);
    } @catch (NSException *e) {}

    @try {
        NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
        if (tags && tags.count > 0) {
            NSMutableArray *tagNames = [NSMutableArray array];
            for (id tag in tags) {
                NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
                if (name) [tagNames addObject:name];
            }
            dict[@"hashtags"] = tagNames;
        }
    } @catch (NSException *e) {}

    @try {
        NSString *val_timeZone = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("timeZone"));
        if (val_timeZone) dict[@"timeZone"] = val_timeZone;
    } @catch (NSException *e) {}

    @try {
        id assignCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("assignmentContext"));
        if (assignCtx) {
            NSSet *assignSet = ((id (*)(id, SEL))objc_msgSend)(assignCtx, sel_registerName("assignments"));
            if (assignSet && assignSet.count > 0) {
                NSMutableArray *assignArr = [NSMutableArray array];
                for (id a in assignSet) {
                    NSMutableDictionary *aDict = [NSMutableDictionary dictionary];
                    @try {
                        id assigneeID = ((id (*)(id, SEL))objc_msgSend)(a, sel_registerName("assigneeID"));
                        if (assigneeID) aDict[@"assigneeID"] = objectIDToString(assigneeID);
                    } @catch (NSException *e2) {}
                    @try {
                        id originatorID = ((id (*)(id, SEL))objc_msgSend)(a, sel_registerName("originatorID"));
                        if (originatorID) aDict[@"originatorID"] = objectIDToString(originatorID);
                    } @catch (NSException *e2) {}
                    @try {
                        NSInteger status = ((NSInteger (*)(id, SEL))objc_msgSend)(a, sel_registerName("status"));
                        aDict[@"status"] = @(status);
                    } @catch (NSException *e2) {}
                    @try {
                        NSDate *assignedDate = ((id (*)(id, SEL))objc_msgSend)(a, sel_registerName("assignedDate"));
                        if (assignedDate) aDict[@"assignedDate"] = dateToISO(assignedDate);
                    } @catch (NSException *e2) {}
                    if (aDict.count > 0) [assignArr addObject:aDict];
                }
                dict[@"assignments"] = assignArr;
            }
        }
    } @catch (NSException *e) {}

    @try {
        id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
        if (attCtx) {
            NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
            if (urlAtts.count > 0) {
                NSURL *attUrl = ((id (*)(id, SEL))objc_msgSend)(urlAtts[0], sel_registerName("url"));
                if (attUrl) {
                    dict[@"url"] = [attUrl absoluteString];
                    // Extract linkedNoteId from applenotes://showNote?identifier=UUID URLs
                    if ([[[attUrl scheme] lowercaseString] isEqualToString:@"applenotes"] && [[[attUrl host] lowercaseString] isEqualToString:@"shownote"]) {
                        NSURLComponents *comps = [NSURLComponents componentsWithURL:attUrl resolvingAgainstBaseURL:NO];
                        for (NSURLQueryItem *item in comps.queryItems) {
                            if ([item.name isEqualToString:@"identifier"] && item.value) {
                                dict[@"linkedNoteId"] = item.value;
                                break;
                            }
                        }
                    }
                }
            }
        }
    } @catch (NSException *e) {}

    // Apply --fields / --full / omit-when-default shaping before returning.
    id shaped = applyOutputShape(dict);
    if ([shaped isKindOfClass:[NSMutableDictionary class]]) return (NSMutableDictionary *)shaped;
    NSMutableDictionary *m = [shaped mutableCopy];
    return m;
}


// --- Commands ---

static int cmdLists(id store) {
    NSArray *lists = fetchLists(store);
    NSMutableArray *result = [NSMutableArray array];
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        id objID = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("objectID"));
        NSMutableDictionary *d = [NSMutableDictionary dictionary];
        if (name) d[@"name"] = name;
        if (objID) {
            if (gOutputFull) {
                // Exact legacy bytes for byte-compat, plus "uuid" as a new addition.
                d[@"id"] = objectIDToLegacyString(objID) ?: @"";
                NSString *uuid = objectIDToUUID(objID);
                if (uuid) d[@"uuid"] = uuid;
            } else {
                NSString *uuid = objectIDToUUID(objID);
                d[@"id"] = uuid ?: (objectIDToString(objID) ?: @"");
                NSString *uri = objectIDToURI(objID);
                if (uri) d[@"uri"] = uri;
            }
        }
        [result addObject:(NSDictionary *)applyOutputShape(d)];
    }
    printJSON(result);
    return 0;
}

static NSSet *parseCommaSeparatedTags(NSString *tagStr) {
    if (!tagStr || tagStr.length == 0) return nil;
    NSArray *parts = [tagStr componentsSeparatedByString:@","];
    NSMutableSet *tags = [NSMutableSet set];
    for (NSString *part in parts) {
        NSString *trimmed = [part stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
        if (trimmed.length > 0) [tags addObject:trimmed];
    }
    return tags.count > 0 ? tags : nil;
}

static NSSet *getTagNames(id rem) {
    @try {
        NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
        if (!tags || tags.count == 0) return [NSSet set];
        NSMutableSet *names = [NSMutableSet set];
        for (id tag in tags) {
            NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
            if (name) [names addObject:name];
        }
        return names;
    } @catch (NSException *e) {
        return [NSSet set];
    }
}

static int cmdList(id store, NSString *listName, BOOL includeCompleted, NSString *tagFilter, NSString *excludeTagFilter, BOOL hasURL, NSString *notesContains) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
    NSArray *rems = fetchReminders(store, list, includeCompleted);

    NSSet *includeTags = parseCommaSeparatedTags(tagFilter);
    NSSet *excludeTags = parseCommaSeparatedTags(excludeTagFilter);
    NSString *lowerNotesFilter = notesContains ? [notesContains lowercaseString] : nil;

    NSMutableArray *result = [NSMutableArray array];
    for (id rem in rems) {
        if (hasURL) {
            @try {
                id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                if (!attCtx) continue;
                NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                if (!urlAtts || urlAtts.count == 0) continue;
            } @catch (NSException *e) { continue; }
        }
        if (includeTags || excludeTags) {
            NSSet *remTags = getTagNames(rem);
            if (includeTags && ![includeTags intersectsSet:remTags]) continue;
            if (excludeTags && [excludeTags intersectsSet:remTags]) continue;
        }
        if (lowerNotesFilter) {
            @try {
                NSString *notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
                if (!notes || [[notes lowercaseString] rangeOfString:lowerNotesFilter].location == NSNotFound) continue;
            } @catch (NSException *e) { continue; }
        }
        [result addObject:reminderToDict(rem)];
    }
    printJSON(result);
    return 0;
}

static int cmdListAll(id store, BOOL includeCompleted, NSString *tagFilter, NSString *excludeTagFilter, BOOL hasURL, NSString *notesContains) {
    NSArray *lists = fetchLists(store);
    NSSet *includeTags = parseCommaSeparatedTags(tagFilter);
    NSSet *excludeTags = parseCommaSeparatedTags(excludeTagFilter);
    NSString *lowerNotesFilter = notesContains ? [notesContains lowercaseString] : nil;

    NSMutableArray *result = [NSMutableArray array];
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        NSArray *rems = fetchReminders(store, list, includeCompleted);
        for (id rem in rems) {
            if (hasURL) {
                @try {
                    id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                    if (!attCtx) continue;
                    NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                    if (!urlAtts || urlAtts.count == 0) continue;
                } @catch (NSException *e) { continue; }
            }
            if (includeTags || excludeTags) {
                NSSet *remTags = getTagNames(rem);
                if (includeTags && ![includeTags intersectsSet:remTags]) continue;
                if (excludeTags && [excludeTags intersectsSet:remTags]) continue;
            }
            if (lowerNotesFilter) {
                @try {
                    NSString *notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
                    if (!notes || [[notes lowercaseString] rangeOfString:lowerNotesFilter].location == NSNotFound) continue;
                } @catch (NSException *e) { continue; }
            }
            NSMutableDictionary *dict = [reminderToDict(rem) mutableCopy];
            addFieldIfRequested(dict, @"listName", name ?: @"");
            [result addObject:dict];
        }
    }
    printJSON(result);
    return 0;
}

// Sort an array of reminder objects by their position in the list's reminderIDsMergeableOrdering.
// Reminders not in the ordered set sort last (preserving relative fetch order among them).
static void sortRemindersByListOrdering(NSMutableArray *reminders, id list) {
    if (reminders.count < 2) return;
    id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
    if (!storage) return;
    id ordering = nil;
    @try {
        ordering = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("reminderIDsMergeableOrdering"));
    } @catch (NSException *e) { return; }
    if (!ordering || ![ordering isKindOfClass:[NSOrderedSet class]]) return;
    NSOrderedSet *orderedSet = (NSOrderedSet *)ordering;
    [reminders sortWithOptions:NSSortStable usingComparator:^NSComparisonResult(id a, id b) {
        id aID = ((id (*)(id, SEL))objc_msgSend)(a, sel_registerName("objectID"));
        id bID = ((id (*)(id, SEL))objc_msgSend)(b, sel_registerName("objectID"));
        NSUInteger aIdx = [orderedSet indexOfObject:aID];
        NSUInteger bIdx = [orderedSet indexOfObject:bID];
        if (aIdx == NSNotFound) aIdx = NSUIntegerMax;
        if (bIdx == NSNotFound) bIdx = NSUIntegerMax;
        if (aIdx < bIdx) return NSOrderedAscending;
        if (aIdx > bIdx) return NSOrderedDescending;
        return NSOrderedSame;
    }];
}

static int cmdGetByID(id store, NSString *remID) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    NSMutableDictionary *dict = [reminderToDict(rem) mutableCopy];

    // Add subtasks
    id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
    NSString *parentIDStr = objectIDToString(parentObjID);
    id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
    NSError *error = nil;
    NSArray *allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listID], &error);

    NSMutableArray *subtaskRems = [NSMutableArray array];
    for (id sub in allInList) {
        id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
        if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
            [subtaskRems addObject:sub];
        }
    }
    if (subtaskRems.count > 0) {
        id list = findListByObjectID(store, listID);
        if (list) sortRemindersByListOrdering(subtaskRems, list);
        NSMutableArray *subtasks = [NSMutableArray array];
        for (id sub in subtaskRems) [subtasks addObject:reminderToDict(sub)];
        addFieldIfRequested(dict, @"subtasks", subtasks);
    }

    printJSON(dict);
    return 0;
}

static int cmdGet(id store, NSString *title, NSString *listName, NSString *urlFilter, NSString *tagFilter, NSString *excludeTagFilter, BOOL filterHasURL, NSString *notesContains) {
    NSArray *matches;
    if (urlFilter) {
        matches = findRemindersByURL(store, urlFilter, listName);
        if (title) {
            // Filter by both URL and title
            NSString *normalizedTitle = normalizeQuotes(title);
            NSString *lowerTitle = [normalizedTitle lowercaseString];
            NSMutableArray *filtered = [NSMutableArray array];
            for (id rem in matches) {
                NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
                if (!t) continue;
                NSString *lowerT = [[normalizeQuotes(t) lowercaseString] copy];
                if ([lowerT rangeOfString:lowerTitle].location != NSNotFound) {
                    [filtered addObject:rem];
                }
            }
            matches = filtered;
        }
    } else if (title) {
        matches = findReminders(store, title, listName);
    } else {
        // No title or URL - fetch all reminders across lists
        NSArray *lists;
        if (listName) {
            id list = findList(store, listName);
            if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
            lists = @[list];
        } else {
            lists = fetchLists(store);
        }
        NSMutableArray *all = [NSMutableArray array];
        for (id list in lists) {
            NSArray *rems = fetchReminders(store, list, NO);
            [all addObjectsFromArray:rems];
        }
        matches = all;
    }

    // Apply tag, has-url, and notes-contains filters
    NSSet *includeTags = parseCommaSeparatedTags(tagFilter);
    NSSet *excludeTags = parseCommaSeparatedTags(excludeTagFilter);
    NSString *lowerNotesFilter = notesContains ? [notesContains lowercaseString] : nil;
    if (filterHasURL || includeTags || excludeTags || lowerNotesFilter) {
        NSMutableArray *filtered = [NSMutableArray array];
        for (id rem in matches) {
            if (filterHasURL) {
                @try {
                    id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                    if (!attCtx) continue;
                    NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                    if (!urlAtts || urlAtts.count == 0) continue;
                } @catch (NSException *e) { continue; }
            }
            if (includeTags || excludeTags) {
                NSSet *remTags = getTagNames(rem);
                if (includeTags && ![includeTags intersectsSet:remTags]) continue;
                if (excludeTags && [excludeTags intersectsSet:remTags]) continue;
            }
            if (lowerNotesFilter) {
                @try {
                    NSString *notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
                    if (!notes || [[notes lowercaseString] rangeOfString:lowerNotesFilter].location == NSNotFound) continue;
                } @catch (NSException *e) { continue; }
            }
            [filtered addObject:rem];
        }
        matches = filtered;
    }

    if (matches.count == 0) {
        // Filter-only queries (no title/url) return empty array instead of error
        if (!title && !urlFilter) {
            printJSON(@[]);
            return 0;
        }
        NSString *desc = urlFilter ? urlFilter : title;
        errorExit([NSString stringWithFormat:@"No reminders found matching: %@", desc]);
    }

    // Skip expensive subtask expansion for bulk filter-only searches
    BOOL expandSubtasks = (title || urlFilter);
    NSMutableDictionary *listCache = expandSubtasks ? [NSMutableDictionary dictionary] : nil;
    NSMutableDictionary *listObjCache = expandSubtasks ? [NSMutableDictionary dictionary] : nil;
    NSMutableArray *resultArray = [NSMutableArray array];
    for (id rem in matches) {
        NSMutableDictionary *dict = [reminderToDict(rem) mutableCopy];

        if (expandSubtasks) {
            // Add subtasks (cached per list to avoid redundant fetches)
            id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
            NSString *parentIDStr = objectIDToString(parentObjID);
            id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
            NSString *listKey = objectIDToString(listID);
            NSArray *allInList = listCache[listKey];
            if (!allInList) {
                NSError *error = nil;
                allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
                    store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
                    @[listID], &error);
                if (allInList) listCache[listKey] = allInList;
                id listObj = findListByObjectID(store, listID);
                if (listObj) listObjCache[listKey] = listObj;
            }

            NSMutableArray *subtaskRems = [NSMutableArray array];
            for (id sub in allInList ?: @[]) {
                id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
                if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
                    [subtaskRems addObject:sub];
                }
            }
            if (subtaskRems.count > 0) {
                id listObj = listObjCache[listKey];
                if (listObj) sortRemindersByListOrdering(subtaskRems, listObj);
                NSMutableArray *subtasks = [NSMutableArray array];
                for (id sub in subtaskRems) [subtasks addObject:reminderToDict(sub)];
                addFieldIfRequested(dict, @"subtasks", subtasks);
            }
        }

        [resultArray addObject:dict];
    }

    if (resultArray.count == 1) {
        printJSON(resultArray[0]);
    } else {
        printJSON(resultArray);
    }
    return 0;
}

static int cmdSubtasks(id store, NSString *title, NSString *listName) {
    id rem = requireUniqueReminder(store, title, listName);

    id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
    NSString *parentIDStr = objectIDToString(parentObjID);
    id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
    NSError *error = nil;
    NSArray *allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listID], &error);

    NSMutableArray *subtaskRems = [NSMutableArray array];
    for (id sub in allInList) {
        id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
        if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
            [subtaskRems addObject:sub];
        }
    }
    id list = findListByObjectID(store, listID);
    if (list) sortRemindersByListOrdering(subtaskRems, list);
    NSMutableArray *subtasks = [NSMutableArray array];
    for (id sub in subtaskRems) [subtasks addObject:reminderToDict(sub)];
    printJSON(subtasks);
    return 0;
}

// Find list by objectID string. Returns nil if not found.
static id findListByObjectID(id store, id targetObjID) {
    NSArray *allLists = fetchLists(store);
    for (id l in allLists) {
        id lID = ((id (*)(id, SEL))objc_msgSend)(l, sel_registerName("objectID"));
        if ([objectIDToString(lID) isEqualToString:objectIDToString(targetObjID)]) {
            return l;
        }
    }
    return nil;
}

// Shared helper: reparent a reminder change item under a parent.
// When afterSiblingCI is non-nil, inserts the child after that sibling in display order
// using REMReminderSubtaskContextChangeItem. Otherwise falls back to _reassignReminderChangeItem.
static void reparentChangeItem(id store, id saveReq, id listCI, id childCI, NSString *parentID) {
    reparentChangeItemAfter(store, saveReq, listCI, childCI, parentID, nil);
}

static void reparentChangeItemAfter(id store, id saveReq, id listCI, id childCI, NSString *parentID, id afterSiblingCI) {
    id parentRem = findReminderByID(store, parentID);
    if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", parentID]);

    id parentCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), parentRem);

    id subtaskCtx = ((id (*)(id, SEL))objc_msgSend)(parentCI, sel_registerName("subtaskContext"));
    if (subtaskCtx) {
        if (afterSiblingCI) {
            // Insert after a specific sibling (preserves batch order)
            ((void (*)(id, SEL, id, id))objc_msgSend)(
                subtaskCtx, sel_registerName("insertReminderChangeItem:afterReminderChangeItem:"),
                childCI, afterSiblingCI);
        } else {
            // Append to end of parent's subtask list (first subtask or standalone add)
            ((void (*)(id, SEL, id))objc_msgSend)(
                subtaskCtx, sel_registerName("addReminderChangeItem:"),
                childCI);
        }
        return;
    }

    // Fallback: unordered reparent (subtaskContext unavailable)
    ((void (*)(id, SEL, id, id))objc_msgSend)(
        listCI, sel_registerName("_reassignReminderChangeItem:withParentReminderChangeItem:"),
        childCI, parentCI);
}

static void reparentChangeItemBefore(id store, id saveReq, id listCI, id childCI, NSString *parentID, id beforeSiblingCI) {
    id parentRem = findReminderByID(store, parentID);
    if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", parentID]);

    id parentCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), parentRem);

    id subtaskCtx = ((id (*)(id, SEL))objc_msgSend)(parentCI, sel_registerName("subtaskContext"));
    if (subtaskCtx) {
        ((void (*)(id, SEL, id, id))objc_msgSend)(
            subtaskCtx, sel_registerName("insertReminderChangeItem:beforeReminderChangeItem:"),
            childCI, beforeSiblingCI);
        return;
    }

    // Fallback: unordered reparent (subtaskContext unavailable)
    ((void (*)(id, SEL, id, id))objc_msgSend)(
        listCI, sel_registerName("_reassignReminderChangeItem:withParentReminderChangeItem:"),
        childCI, parentCI);
}

// Fetch a parent's subtasks sorted by list ordering. Returns an NSMutableArray of reminder objects.
static NSMutableArray *fetchSortedSubtasks(id store, id parentRem) {
    id parentObjID = ((id (*)(id, SEL))objc_msgSend)(parentRem, sel_registerName("objectID"));
    NSString *parentIDStr = objectIDToString(parentObjID);
    id listID = ((id (*)(id, SEL))objc_msgSend)(parentRem, sel_registerName("listID"));
    NSError *error = nil;
    NSArray *allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listID], &error);

    NSMutableArray *subtaskRems = [NSMutableArray array];
    for (id sub in allInList) {
        id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
        if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
            [subtaskRems addObject:sub];
        }
    }
    id list = findListByObjectID(store, listID);
    if (list) sortRemindersByListOrdering(subtaskRems, list);
    return subtaskRems;
}

static int cmdAdd(id store, NSString *title, NSString *listName, NSDictionary *opts) {
    id list = nil;
    NSString *parentID = opts[@"parent-id"];

    if (parentID) {
        // Look up parent to derive/validate list
        id parentRem = findReminderByID(store, parentID);
        if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", parentID]);

        id parentListID = ((id (*)(id, SEL))objc_msgSend)(parentRem, sel_registerName("listID"));
        list = findListByObjectID(store, parentListID);
        if (!list) errorExit(@"Could not find parent's list");

        // If --list was also specified, validate it matches
        if (listName) {
            id specifiedList = findList(store, listName);
            if (!specifiedList) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
            id specListID = ((id (*)(id, SEL))objc_msgSend)(specifiedList, sel_registerName("objectID"));
            if (![objectIDToString(specListID) isEqualToString:objectIDToString(parentListID)]) {
                errorExit(@"--parent-id and --list conflict: parent is in a different list. Omit --list to auto-derive from parent.");
            }
        }
    } else {
        list = listName ? findList(store, listName) : [fetchLists(store) firstObject];
    }
    if (!list) errorExit(@"No list found");

    // Get the list change item from save request
    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    id newRem = ((id (*)(id, SEL, id, id))objc_msgSend)(
        saveReq, sel_registerName("addReminderWithTitle:toListChangeItem:"),
        title, listCI);

    if (!newRem) errorExit(@"Failed to create reminder");

    // Apply optional properties
    if (opts[@"notes"]) {
        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("setNotesAsString:"), opts[@"notes"]);
    }
    if (opts[@"completed"]) {
        BOOL val = parseBoolString(opts[@"completed"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(newRem, sel_registerName("setCompleted:"), val);
    }
    if (opts[@"priority"]) {
        NSUInteger val = [opts[@"priority"] integerValue];
        ((void (*)(id, SEL, NSUInteger))objc_msgSend)(newRem, sel_registerName("setPriority:"), val);
    }
    if (opts[@"flagged"]) {
        BOOL val = parseBoolString(opts[@"flagged"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(newRem, sel_registerName("setFlagged:"), val);
    }
    if (opts[@"due-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"due-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("setDueDateComponents:"), comps);
    }
    if (opts[@"start-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"start-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("setStartDateComponents:"), comps);
    }
    if (opts[@"url"]) {
        NSURL *url = [NSURL URLWithString:opts[@"url"]];
        if (url) {
            id attCtx = ((id (*)(id, SEL))objc_msgSend)(newRem, sel_registerName("attachmentContext"));
            ((void (*)(id, SEL, id))objc_msgSend)(attCtx, sel_registerName("setURLAttachmentWithURL:"), url);
        }
    }

    // Reparent: --parent-id (with optional --after-id or --position for ordering)
    if (opts[@"parent-id"]) {
        NSString *afterID = opts[@"after-id"];
        NSString *positionStr = opts[@"position"];

        if (afterID && positionStr) {
            errorExit(@"Cannot specify both --after-id and --position");
        }

        if (afterID) {
            // Insert after the specified sibling
            id afterRem = findReminderByID(store, afterID);
            if (!afterRem) errorExit([NSString stringWithFormat:@"Sibling not found with id: %@", afterID]);
            id afterCI = ((id (*)(id, SEL, id))objc_msgSend)(
                saveReq, sel_registerName("updateReminder:"), afterRem);
            reparentChangeItemAfter(store, saveReq, listCI, newRem, opts[@"parent-id"], afterCI);
        } else if (positionStr) {
            NSInteger pos = [positionStr integerValue];
            if (pos < 1) errorExit(@"--position must be >= 1");

            id parentRem = findReminderByID(store, opts[@"parent-id"]);
            if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", opts[@"parent-id"]]);
            NSMutableArray *siblings = fetchSortedSubtasks(store, parentRem);

            if (pos == 1 && siblings.count > 0) {
                // Insert before the current first subtask
                id firstSibling = siblings[0];
                id firstCI = ((id (*)(id, SEL, id))objc_msgSend)(
                    saveReq, sel_registerName("updateReminder:"), firstSibling);
                reparentChangeItemBefore(store, saveReq, listCI, newRem, opts[@"parent-id"], firstCI);
            } else if (pos <= (NSInteger)siblings.count) {
                // Insert after the sibling at position N-1
                id prevSibling = siblings[pos - 1];
                id prevCI = ((id (*)(id, SEL, id))objc_msgSend)(
                    saveReq, sel_registerName("updateReminder:"), prevSibling);
                reparentChangeItemAfter(store, saveReq, listCI, newRem, opts[@"parent-id"], prevCI);
            } else {
                // Position exceeds count: append to end
                reparentChangeItem(store, saveReq, listCI, newRem, opts[@"parent-id"]);
            }
        } else {
            reparentChangeItem(store, saveReq, listCI, newRem, opts[@"parent-id"]);
        }
    }

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    // Re-fetch and return — use the resolved list name for accurate lookup
    // (when --parent-id is used without --list, listName is nil but list was derived from parent)
    NSString *resolvedListName = listName;
    if (!resolvedListName) {
        id listStorage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        resolvedListName = ((id (*)(id, SEL))objc_msgSend)(listStorage, sel_registerName("name"));
    }
    id created = findReminder(store, title, resolvedListName);
    if (created) printJSON(reminderToDict(created));
    else fprintf(stderr, "Created (but could not re-fetch)\n");
    return 0;
}

static int cmdCreateList(id store, NSString *name) {
    // Get default account from the first list
    NSArray *lists = fetchLists(store);
    if (lists.count == 0) errorExit(@"No accounts found");
    id account = ((id (*)(id, SEL))objc_msgSend)(lists[0], sel_registerName("account"));

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id accountCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateAccount:"), account);

    id newList = ((id (*)(id, SEL, id, id, id))objc_msgSend)(
        saveReq, sel_registerName("addListWithName:toAccountChangeItem:listObjectID:"),
        name, accountCI, nil);

    if (!newList) errorExit(@"Failed to create list");

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"name": name, @"created": @YES});
    return 0;
}

static int cmdRenameList(id store, NSString *oldName, NSString *newName) {
    id list = findList(store, oldName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", oldName]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    id storage = ((id (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("storage"));
    ((void (*)(id, SEL, id))objc_msgSend)(storage, sel_registerName("setName:"), newName);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"oldName": oldName, @"newName": newName, @"renamed": @YES});
    return 0;
}

static int cmdDeleteList(id store, NSString *name) {
    id list = findList(store, name);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", name]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    ((void (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("removeFromParent"));

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"name": name, @"deleted": @YES});
    return 0;
}

static int cmdAddTag(id store, NSString *remID, NSString *tagName) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    // Check if tag already exists (idempotent add)
    NSSet *existingTags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
    if (existingTags) {
        for (id tag in existingTags) {
            NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
            if ([name isEqualToString:tagName]) {
                // Tag already exists, return current state (no-op)
                printJSON(reminderToDict(rem));
                return 0;
            }
        }
    }

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    id hashtagCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("hashtagContext"));
    if (!hashtagCtx) errorExit(@"Failed to get hashtag context");

    // type 0 = normal tag
    ((void (*)(id, SEL, NSUInteger, id))objc_msgSend)(
        hashtagCtx, sel_registerName("addHashtagWithType:name:"), (NSUInteger)0, tagName);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    id updated = findReminderByID(store, remID);
    if (updated) printJSON(reminderToDict(updated));
    else printJSON(@{@"id": remID, @"tagAdded": tagName});
    return 0;
}

static int cmdRemoveTag(id store, NSString *remID, NSString *tagName) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    id hashtagCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("hashtagContext"));
    if (!hashtagCtx) errorExit(@"Failed to get hashtag context");

    // Find the hashtag object by name from the reminder's existing hashtags
    NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
    id tagToRemove = nil;
    for (id tag in tags) {
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
        if ([name isEqualToString:tagName]) { tagToRemove = tag; break; }
    }
    if (!tagToRemove) errorExit([NSString stringWithFormat:@"Tag not found: %@", tagName]);

    ((void (*)(id, SEL, id))objc_msgSend)(hashtagCtx, sel_registerName("removeHashtag:"), tagToRemove);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    id updated = findReminderByID(store, remID);
    if (updated) printJSON(reminderToDict(updated));
    else printJSON(@{@"id": remID, @"tagRemoved": tagName});
    return 0;
}

static int cmdListSections(id store, NSString *listName) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);

    // Try to fetch sections from the list
    NSMutableArray *result = [NSMutableArray array];
    @try {
        id sections = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("sections"));
        if (sections) {
            for (id section in sections) {
                NSString *name = ((id (*)(id, SEL))objc_msgSend)(section, sel_registerName("canonicalName"));
                id objID = ((id (*)(id, SEL))objc_msgSend)(section, sel_registerName("objectID"));
                NSMutableDictionary *d = [NSMutableDictionary dictionary];
                if (name) d[@"name"] = name;
                if (objID) {
                    if (gOutputFull) {
                        d[@"id"] = objectIDToLegacyString(objID) ?: @"";
                        NSString *uuid = objectIDToUUID(objID);
                        if (uuid) d[@"uuid"] = uuid;
                    } else {
                        NSString *uuid = objectIDToUUID(objID);
                        d[@"id"] = uuid ?: (objectIDToString(objID) ?: @"");
                        NSString *uri = objectIDToURI(objID);
                        if (uri) d[@"uri"] = uri;
                    }
                }
                [result addObject:d];
            }
        }
    } @catch (NSException *e) {
        fprintf(stderr, "Warning: could not enumerate sections: %s\n", [[e reason] UTF8String]);
    }
    printJSON(result);
    return 0;
}

static int cmdCreateSection(id store, NSString *listName, NSString *sectionName) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    // Create a new section change item
    id newSection = ((id (*)(id, SEL, id, id, id))objc_msgSend)(
        [REMListSectionCIClass alloc],
        sel_registerName("initWithObjectID:displayName:insertIntoListChangeItem:"),
        nil, sectionName, listCI);

    if (!newSection) errorExit(@"Failed to create section");

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"list": listName, @"section": sectionName, @"created": @YES});
    return 0;
}


// --- Update Command (generated from REMINDER_WRITE_OPS) ---

static int cmdUpdate(id store, NSString *listName, NSDictionary *opts) {
    NSString *remID = opts[@"id"];
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    // Validate conflicting URL flags
    if (opts[@"url"] && opts[@"clear-url"]) {
        errorExit(@"Cannot use --url and --clear-url together");
    }

    // Validate conflicting parent flags
    NSString *parentID = opts[@"parent-id"];
    BOOL removeParent = opts[@"remove-parent"] != nil;
    if (parentID && removeParent) {
        errorExit(@"Cannot specify both --parent-id and --remove-parent");
    }

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    if (opts[@"title"]) {
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setTitleAsString:"), opts[@"title"]);
    }
    if (opts[@"append-notes"]) {
        NSString *existing = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
        NSString *combined;
        if (existing && [existing length] > 0) {
            combined = [NSString stringWithFormat:@"%@\n%@", existing, opts[@"append-notes"]];
        } else {
            combined = opts[@"append-notes"];
        }
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setNotesAsString:"), combined);
    } else if (opts[@"notes"]) {
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setNotesAsString:"), opts[@"notes"]);
    }
    if (opts[@"completed"]) {
        BOOL val = parseBoolString(opts[@"completed"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("setCompleted:"), val);
    }
    if (opts[@"priority"]) {
        NSUInteger val = [opts[@"priority"] integerValue];
        ((void (*)(id, SEL, NSUInteger))objc_msgSend)(changeItem, sel_registerName("setPriority:"), val);
    }
    if (opts[@"flagged"]) {
        BOOL val = parseBoolString(opts[@"flagged"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("setFlagged:"), val);
    }
    if (opts[@"due-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"due-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setDueDateComponents:"), comps);
    }
    if (opts[@"start-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"start-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setStartDateComponents:"), comps);
    }
    if (opts[@"url"]) {
        NSURL *url = [NSURL URLWithString:opts[@"url"]];
        if (url) {
            id attCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("attachmentContext"));
            ((void (*)(id, SEL, id))objc_msgSend)(attCtx, sel_registerName("setURLAttachmentWithURL:"), url);
        }
    }
    if (opts[@"clear-url"]) {
        id attCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("attachmentContext"));
        ((void (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("removeURLAttachments"));
    }
    if (opts[@"remove-parent"]) {
        ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("removeFromParentReminder"));
    }
    if (opts[@"remove-from-list"]) {
        ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("removeFromList"));
    }

    // Reparent: --parent-id
    if (parentID) {
        // Validate no self-parenting (update-specific)
        id remObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
        id parentRem = findReminderByID(store, parentID);
        if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", parentID]);
        id parentObjID = ((id (*)(id, SEL))objc_msgSend)(parentRem, sel_registerName("objectID"));
        if ([objectIDToString(remObjID) isEqualToString:objectIDToString(parentObjID)]) {
            errorExit(@"Cannot set a reminder as its own parent");
        }

        // Get the list for reparenting using shared helper
        id remListID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
        id targetList = findListByObjectID(store, remListID);
        if (!targetList) errorExit(@"Could not find list for reparenting");

        id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
            saveReq, sel_registerName("updateList:"), targetList);

        reparentChangeItem(store, saveReq, listCI, changeItem, parentID);
    }

    // Move to different list: --to-list
    NSString *toListName = opts[@"to-list"];
    if (toListName) {
        id destList = findList(store, toListName);
        if (!destList) errorExit([NSString stringWithFormat:@"Destination list not found: %@", toListName]);

        id destListCI = ((id (*)(id, SEL, id))objc_msgSend)(
            saveReq, sel_registerName("updateList:"), destList);

        // Use initWithReminderChangeItem:insertIntoListChangeItem: to move
        Class REMReminderCIClass = NSClassFromString(@"REMReminderChangeItem");
        id moveCI = ((id (*)(id, SEL, id, id))objc_msgSend)(
            [REMReminderCIClass alloc],
            sel_registerName("initWithReminderChangeItem:insertIntoListChangeItem:"),
            changeItem, destListCI);
        if (!moveCI) errorExit(@"Failed to create move operation");
    }

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    // Re-fetch and return updated state
    id updated = findReminderByID(store, remID);
    if (updated) printJSON(reminderToDict(updated));
    else fprintf(stderr, "Updated successfully\n");
    return 0;
}


static int cmdComplete(id store, NSString *remID) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("setCompleted:"), YES);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"id": remID, @"completed": @YES});
    return 0;
}



static int cmdDelete(id store, NSString *remID) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("removeFromList"));

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"id": remID, @"deleted": @YES});
    return 0;
}


// --- Link Note Command ---

static int cmdLinkNote(id store, NSString *remId, NSString *noteId) {
    // Construct applenotes:// URL
    NSURLComponents *comps = [[NSURLComponents alloc] init];
    comps.scheme = @"applenotes";
    comps.host = @"showNote";
    comps.queryItems = @[[NSURLQueryItem queryItemWithName:@"identifier" value:noteId]];
    NSString *urlStr = [comps string];

    // Delegate to cmdUpdate with the constructed URL
    return cmdUpdate(store, nil, @{@"id": remId, @"url": urlStr});
}

