// AUTO-GENERATED by generate-cli.py — do not edit manually

#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <objc/message.h>
#include <mach-o/dyld.h>
#include <unistd.h>
#include <sys/wait.h>
#include <spawn.h>
#include <fcntl.h>

// --- Framework Loading ---

static Class REMStoreClass;
static Class REMSaveRequestClass;
static Class REMListSectionCIClass;

static void loadFramework(void) {
    [[NSBundle bundleWithPath:@"/System/Library/PrivateFrameworks/ReminderKit.framework"] load];
    REMStoreClass = NSClassFromString(@"REMStore");
    REMSaveRequestClass = NSClassFromString(@"REMSaveRequest");
    REMListSectionCIClass = NSClassFromString(@"REMListSectionChangeItem");
}

static id getStore(void) {
    return ((id (*)(id, SEL, BOOL))objc_msgSend)(
        [REMStoreClass alloc], sel_registerName("initUserInteractive:"), YES);
}

// --- Helpers ---

static void errorExit(NSString *msg) {
    fprintf(stderr, "Error: %s\n", [msg UTF8String]);
    exit(1);
}

static BOOL parseBoolString(NSString *str) {
    NSString *lower = [str lowercaseString];
    return [lower isEqualToString:@"true"] || [lower isEqualToString:@"1"] || [lower isEqualToString:@"yes"];
}

static NSString *objectIDToString(id objID) {
    if (!objID) return nil;
    return [objID description];
}

static NSString *dateToISO(NSDate *date) {
    if (!date) return nil;
    NSISO8601DateFormatter *fmt = [[NSISO8601DateFormatter alloc] init];
    return [fmt stringFromDate:date];
}

static NSString *dateCompsToString(NSDateComponents *comps) {
    if (!comps) return nil;
    NSCalendar *cal = [NSCalendar currentCalendar];
    NSDate *date = [cal dateFromComponents:comps];
    if (date) return dateToISO(date);
    // Fallback: manual formatting
    return [NSString stringWithFormat:@"%04ld-%02ld-%02ld",
        (long)[comps year], (long)[comps month], (long)[comps day]];
}

static NSDateComponents *stringToDateComps(NSString *str) {
    // Parse ISO date string like "2026-03-15" or "2026-03-15T10:00:00"
    NSDateComponents *comps = [[NSDateComponents alloc] init];
    NSArray *parts = [str componentsSeparatedByString:@"T"];
    NSArray *dateParts = [parts[0] componentsSeparatedByString:@"-"];
    if (dateParts.count >= 3) {
        comps.year = [dateParts[0] integerValue];
        comps.month = [dateParts[1] integerValue];
        comps.day = [dateParts[2] integerValue];
    }
    if (parts.count > 1) {
        NSArray *timeParts = [parts[1] componentsSeparatedByString:@":"];
        if (timeParts.count >= 2) {
            comps.hour = [timeParts[0] integerValue];
            comps.minute = [timeParts[1] integerValue];
        }
    }
    return comps;
}

static NSString *normalizeQuotes(NSString *str) {
    if (!str) return nil;
    NSString *result = [str stringByReplacingOccurrencesOfString:@"\u2018" withString:@"'"];
    result = [result stringByReplacingOccurrencesOfString:@"\u2019" withString:@"'"];
    return result;
}

static void printJSON(id obj) {
    NSError *error = nil;
    NSData *data = [NSJSONSerialization dataWithJSONObject:obj
        options:NSJSONWritingPrettyPrinted | NSJSONWritingSortedKeys error:&error];
    if (error) errorExit([error localizedDescription]);
    printf("%s\n", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding].UTF8String);
}

// --- List Helpers ---

static NSArray *fetchLists(id store) {
    NSError *error = nil;
    NSArray *lists = ((id (*)(id, SEL, id*))objc_msgSend)(
        store, sel_registerName("fetchEligibleDefaultListsWithError:"), &error);
    if (error) {
        if ([[error domain] isEqualToString:@"NSCocoaErrorDomain"] && [error code] == 4097) {
            fprintf(stderr, "Error: Reminders access denied.\n\n");
            fprintf(stderr, "Your terminal app needs permission to access Reminders.\n\n");
            fprintf(stderr, "1. Grant permission (triggers macOS prompt):\n");
            fprintf(stderr, "   osascript -e 'tell application \"Reminders\" to get name of every list'\n\n");
            fprintf(stderr, "2. If previously denied, reset first, then re-run step 1:\n");
            fprintf(stderr, "   tccutil reset Reminders <bundle-id>\n\n");
            fprintf(stderr, "   Find your terminal's bundle ID:\n");
            fprintf(stderr, "   osascript -e 'id of app \"iTerm\"'  (replace iTerm with your terminal app name)\n\n");
            fprintf(stderr, "3. Then retry: reminderkit lists\n");
            exit(1);
        }
        errorExit([NSString stringWithFormat:@"Failed to fetch lists: %@", error]);
    }
    return lists;
}

static id findList(id store, NSString *name) {
    NSArray *lists = fetchLists(store);
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *listName = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        if ([listName isEqualToString:name]) return list;
    }
    // Normalized fallback: retry with curly quotes normalized to straight quotes
    NSString *normalizedName = normalizeQuotes(name);
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *listName = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        if ([normalizeQuotes(listName) isEqualToString:normalizedName]) return list;
    }
    return nil;
}

static NSArray *fetchReminders(id store, id list, BOOL includeCompleted) {
    id listObjID = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("objectID"));
    NSError *error = nil;
    NSArray *all = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listObjID], &error);
    if (error) errorExit([NSString stringWithFormat:@"Failed to fetch reminders: %@", error]);
    if (includeCompleted) return all;
    NSMutableArray *incomplete = [NSMutableArray array];
    for (id rem in all) {
        BOOL done = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isCompleted"));
        if (!done) [incomplete addObject:rem];
    }
    return incomplete;
}

static id findReminder(id store, NSString *title, NSString *listName) {
    NSArray *lists;
    if (listName) {
        id list = findList(store, listName);
        if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
        lists = @[list];
    } else {
        lists = fetchLists(store);
    }
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, YES);
        for (id rem in rems) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            if ([t isEqualToString:title]) return rem;
        }
    }
    // Normalized fallback: retry with curly quotes normalized to straight quotes
    NSString *normalizedTitle = normalizeQuotes(title);
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, YES);
        for (id rem in rems) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            if ([normalizeQuotes(t) isEqualToString:normalizedTitle]) return rem;
        }
    }
    return nil;
}

static NSString *normalizeURL(NSString *url) {
    // Strip trailing slash for comparison
    while ([url hasSuffix:@"/"]) {
        url = [url substringToIndex:url.length - 1];
    }
    return [url lowercaseString];
}

static NSArray *findReminders(id store, NSString *title, NSString *listName) {
    NSArray *lists;
    if (listName) {
        id list = findList(store, listName);
        if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
        lists = @[list];
    } else {
        lists = fetchLists(store);
    }
    NSMutableArray *results = [NSMutableArray array];
    NSString *normalizedTitle = normalizeQuotes(title);
    NSString *lowerTitle = [normalizedTitle lowercaseString];
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, NO);
        for (id rem in rems) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            if (!t) continue;
            NSString *lowerT = [[normalizeQuotes(t) lowercaseString] copy];
            if ([lowerT rangeOfString:lowerTitle].location != NSNotFound) {
                [results addObject:rem];
            }
        }
    }
    return results;
}

static NSArray *findRemindersByURL(id store, NSString *url, NSString *listName) {
    NSArray *lists;
    if (listName) {
        id list = findList(store, listName);
        if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
        lists = @[list];
    } else {
        lists = fetchLists(store);
    }
    NSMutableArray *results = [NSMutableArray array];
    NSString *normalizedSearch = normalizeURL(url);
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, NO);
        for (id rem in rems) {
            @try {
                id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                if (!attCtx) continue;
                NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                if (urlAtts.count == 0) continue;
                NSURL *attUrl = ((id (*)(id, SEL))objc_msgSend)(urlAtts[0], sel_registerName("url"));
                if (!attUrl) continue;
                NSString *normalizedAtt = normalizeURL([attUrl absoluteString]);
                if ([normalizedAtt isEqualToString:normalizedSearch]) {
                    [results addObject:rem];
                }
            } @catch (NSException *e) {}
        }
    }
    return results;
}

static id findReminderByID(id store, NSString *idString) {
    NSArray *lists = fetchLists(store);
    for (id list in lists) {
        NSArray *rems = fetchReminders(store, list, YES);
        for (id rem in rems) {
            id objID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
            NSString *idStr = objectIDToString(objID);
            if (idStr && [idStr isEqualToString:idString]) return rem;
        }
    }
    return nil;
}

static id requireUniqueReminder(id store, NSString *title, NSString *listName) {
    NSArray *matches = findReminders(store, title, listName);
    if (matches.count == 0) {
        errorExit([NSString stringWithFormat:@"Reminder not found: %@", title]);
    }
    if (matches.count > 1) {
        NSMutableString *msg = [NSMutableString stringWithFormat:@"Multiple reminders match '%@'. Use --id to specify:\n", title];
        for (id rem in matches) {
            NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
            id objID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
            NSString *idStr = objectIDToString(objID);
            [msg appendFormat:@"  - \"%@\" (id: %@)\n", t, idStr];
        }
        errorExit(msg);
    }
    return matches[0];
}


// --- Reminder Serialization (generated from REMINDER_READ_PROPS) ---

static NSDictionary *reminderToDict(id rem) {
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];

    @try {
        NSString *val_title = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
        if (val_title) dict[@"title"] = val_title;
    } @catch (NSException *e) {}

    @try {
        NSString *val_notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
        if (val_notes) dict[@"notes"] = val_notes;
    } @catch (NSException *e) {}

    @try {
        BOOL val_completed = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isCompleted"));
        dict[@"completed"] = @(val_completed);
    } @catch (NSException *e) {}

    @try {
        NSUInteger val_priority = ((NSUInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("priority"));
        dict[@"priority"] = @(val_priority);
    } @catch (NSException *e) {}

    @try {
        NSInteger val_flagged = ((NSInteger (*)(id, SEL))objc_msgSend)(rem, sel_registerName("flagged"));
        dict[@"flagged"] = @(val_flagged);
    } @catch (NSException *e) {}

    @try {
        BOOL val_allDay = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("allDay"));
        dict[@"allDay"] = @(val_allDay);
    } @catch (NSException *e) {}

    @try {
        BOOL val_isOverdue = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isOverdue"));
        dict[@"isOverdue"] = @(val_isOverdue);
    } @catch (NSException *e) {}

    @try {
        BOOL val_isRecurrent = ((BOOL (*)(id, SEL))objc_msgSend)(rem, sel_registerName("isRecurrent"));
        dict[@"isRecurrent"] = @(val_isRecurrent);
    } @catch (NSException *e) {}

    @try {
        id val_id = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
        if (val_id) dict[@"id"] = objectIDToString(val_id);
    } @catch (NSException *e) {}

    @try {
        id val_listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
        if (val_listID) dict[@"listID"] = objectIDToString(val_listID);
    } @catch (NSException *e) {}

    @try {
        id val_parentID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("parentReminderID"));
        if (val_parentID) dict[@"parentID"] = objectIDToString(val_parentID);
    } @catch (NSException *e) {}

    @try {
        NSDateComponents *val_dueDate = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("dueDateComponents"));
        if (val_dueDate) dict[@"dueDate"] = dateCompsToString(val_dueDate);
    } @catch (NSException *e) {}

    @try {
        NSDateComponents *val_startDate = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("startDateComponents"));
        if (val_startDate) dict[@"startDate"] = dateCompsToString(val_startDate);
    } @catch (NSException *e) {}

    @try {
        NSDate *val_createdAt = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("creationDate"));
        if (val_createdAt) dict[@"createdAt"] = dateToISO(val_createdAt);
    } @catch (NSException *e) {}

    @try {
        NSDate *val_modifiedAt = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("lastModifiedDate"));
        if (val_modifiedAt) dict[@"modifiedAt"] = dateToISO(val_modifiedAt);
    } @catch (NSException *e) {}

    @try {
        NSDate *val_completedAt = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("completionDate"));
        if (val_completedAt) dict[@"completedAt"] = dateToISO(val_completedAt);
    } @catch (NSException *e) {}

    @try {
        NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
        if (tags && tags.count > 0) {
            NSMutableArray *tagNames = [NSMutableArray array];
            for (id tag in tags) {
                NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
                if (name) [tagNames addObject:name];
            }
            dict[@"hashtags"] = tagNames;
        }
    } @catch (NSException *e) {}

    @try {
        NSString *val_timeZone = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("timeZone"));
        if (val_timeZone) dict[@"timeZone"] = val_timeZone;
    } @catch (NSException *e) {}

    @try {
        id assignCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("assignmentContext"));
        if (assignCtx) {
            NSSet *assignSet = ((id (*)(id, SEL))objc_msgSend)(assignCtx, sel_registerName("assignments"));
            if (assignSet && assignSet.count > 0) {
                NSMutableArray *assignArr = [NSMutableArray array];
                for (id a in assignSet) {
                    NSMutableDictionary *aDict = [NSMutableDictionary dictionary];
                    @try {
                        id assigneeID = ((id (*)(id, SEL))objc_msgSend)(a, sel_registerName("assigneeID"));
                        if (assigneeID) aDict[@"assigneeID"] = objectIDToString(assigneeID);
                    } @catch (NSException *e2) {}
                    @try {
                        id originatorID = ((id (*)(id, SEL))objc_msgSend)(a, sel_registerName("originatorID"));
                        if (originatorID) aDict[@"originatorID"] = objectIDToString(originatorID);
                    } @catch (NSException *e2) {}
                    @try {
                        NSInteger status = ((NSInteger (*)(id, SEL))objc_msgSend)(a, sel_registerName("status"));
                        aDict[@"status"] = @(status);
                    } @catch (NSException *e2) {}
                    @try {
                        NSDate *assignedDate = ((id (*)(id, SEL))objc_msgSend)(a, sel_registerName("assignedDate"));
                        if (assignedDate) aDict[@"assignedDate"] = dateToISO(assignedDate);
                    } @catch (NSException *e2) {}
                    if (aDict.count > 0) [assignArr addObject:aDict];
                }
                dict[@"assignments"] = assignArr;
            }
        }
    } @catch (NSException *e) {}

    @try {
        id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
        if (attCtx) {
            NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
            if (urlAtts.count > 0) {
                NSURL *attUrl = ((id (*)(id, SEL))objc_msgSend)(urlAtts[0], sel_registerName("url"));
                if (attUrl) {
                    dict[@"url"] = [attUrl absoluteString];
                    // Extract linkedNoteId from applenotes://showNote?identifier=UUID URLs
                    if ([[[attUrl scheme] lowercaseString] isEqualToString:@"applenotes"] && [[[attUrl host] lowercaseString] isEqualToString:@"shownote"]) {
                        NSURLComponents *comps = [NSURLComponents componentsWithURL:attUrl resolvingAgainstBaseURL:NO];
                        for (NSURLQueryItem *item in comps.queryItems) {
                            if ([item.name isEqualToString:@"identifier"] && item.value) {
                                dict[@"linkedNoteId"] = item.value;
                                break;
                            }
                        }
                    }
                }
            }
        }
    } @catch (NSException *e) {}

    return dict;
}


// --- Commands ---

static int cmdLists(id store) {
    NSArray *lists = fetchLists(store);
    NSMutableArray *result = [NSMutableArray array];
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        id objID = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("objectID"));
        [result addObject:@{@"name": name ?: @"", @"id": objectIDToString(objID) ?: @""}];
    }
    printJSON(result);
    return 0;
}

static NSSet *parseCommaSeparatedTags(NSString *tagStr) {
    if (!tagStr || tagStr.length == 0) return nil;
    NSArray *parts = [tagStr componentsSeparatedByString:@","];
    NSMutableSet *tags = [NSMutableSet set];
    for (NSString *part in parts) {
        NSString *trimmed = [part stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
        if (trimmed.length > 0) [tags addObject:trimmed];
    }
    return tags.count > 0 ? tags : nil;
}

static NSSet *getTagNames(id rem) {
    @try {
        NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
        if (!tags || tags.count == 0) return [NSSet set];
        NSMutableSet *names = [NSMutableSet set];
        for (id tag in tags) {
            NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
            if (name) [names addObject:name];
        }
        return names;
    } @catch (NSException *e) {
        return [NSSet set];
    }
}

static int cmdList(id store, NSString *listName, BOOL includeCompleted, NSString *tagFilter, NSString *excludeTagFilter, BOOL hasURL, NSString *notesContains) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
    NSArray *rems = fetchReminders(store, list, includeCompleted);

    NSSet *includeTags = parseCommaSeparatedTags(tagFilter);
    NSSet *excludeTags = parseCommaSeparatedTags(excludeTagFilter);
    NSString *lowerNotesFilter = notesContains ? [notesContains lowercaseString] : nil;

    NSMutableArray *result = [NSMutableArray array];
    for (id rem in rems) {
        if (hasURL) {
            @try {
                id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                if (!attCtx) continue;
                NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                if (!urlAtts || urlAtts.count == 0) continue;
            } @catch (NSException *e) { continue; }
        }
        if (includeTags || excludeTags) {
            NSSet *remTags = getTagNames(rem);
            if (includeTags && ![includeTags intersectsSet:remTags]) continue;
            if (excludeTags && [excludeTags intersectsSet:remTags]) continue;
        }
        if (lowerNotesFilter) {
            @try {
                NSString *notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
                if (!notes || [[notes lowercaseString] rangeOfString:lowerNotesFilter].location == NSNotFound) continue;
            } @catch (NSException *e) { continue; }
        }
        [result addObject:reminderToDict(rem)];
    }
    printJSON(result);
    return 0;
}

static int cmdListAll(id store, BOOL includeCompleted, NSString *tagFilter, NSString *excludeTagFilter, BOOL hasURL, NSString *notesContains) {
    NSArray *lists = fetchLists(store);
    NSSet *includeTags = parseCommaSeparatedTags(tagFilter);
    NSSet *excludeTags = parseCommaSeparatedTags(excludeTagFilter);
    NSString *lowerNotesFilter = notesContains ? [notesContains lowercaseString] : nil;

    NSMutableArray *result = [NSMutableArray array];
    for (id list in lists) {
        id storage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(storage, sel_registerName("name"));
        NSArray *rems = fetchReminders(store, list, includeCompleted);
        for (id rem in rems) {
            if (hasURL) {
                @try {
                    id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                    if (!attCtx) continue;
                    NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                    if (!urlAtts || urlAtts.count == 0) continue;
                } @catch (NSException *e) { continue; }
            }
            if (includeTags || excludeTags) {
                NSSet *remTags = getTagNames(rem);
                if (includeTags && ![includeTags intersectsSet:remTags]) continue;
                if (excludeTags && [excludeTags intersectsSet:remTags]) continue;
            }
            if (lowerNotesFilter) {
                @try {
                    NSString *notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
                    if (!notes || [[notes lowercaseString] rangeOfString:lowerNotesFilter].location == NSNotFound) continue;
                } @catch (NSException *e) { continue; }
            }
            NSMutableDictionary *dict = [reminderToDict(rem) mutableCopy];
            dict[@"listName"] = name ?: @"";
            [result addObject:dict];
        }
    }
    printJSON(result);
    return 0;
}

static int cmdGetByID(id store, NSString *remID) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    NSMutableDictionary *dict = [reminderToDict(rem) mutableCopy];

    // Add subtasks
    id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
    NSString *parentIDStr = objectIDToString(parentObjID);
    id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
    NSError *error = nil;
    NSArray *allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listID], &error);

    NSMutableArray *subtasks = [NSMutableArray array];
    for (id sub in allInList) {
        id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
        if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
            [subtasks addObject:reminderToDict(sub)];
        }
    }
    if (subtasks.count > 0) dict[@"subtasks"] = subtasks;

    printJSON(dict);
    return 0;
}

static int cmdGet(id store, NSString *title, NSString *listName, NSString *urlFilter, NSString *tagFilter, NSString *excludeTagFilter, BOOL filterHasURL, NSString *notesContains) {
    NSArray *matches;
    if (urlFilter) {
        matches = findRemindersByURL(store, urlFilter, listName);
        if (title) {
            // Filter by both URL and title
            NSString *normalizedTitle = normalizeQuotes(title);
            NSString *lowerTitle = [normalizedTitle lowercaseString];
            NSMutableArray *filtered = [NSMutableArray array];
            for (id rem in matches) {
                NSString *t = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("titleAsString"));
                if (!t) continue;
                NSString *lowerT = [[normalizeQuotes(t) lowercaseString] copy];
                if ([lowerT rangeOfString:lowerTitle].location != NSNotFound) {
                    [filtered addObject:rem];
                }
            }
            matches = filtered;
        }
    } else if (title) {
        matches = findReminders(store, title, listName);
    } else {
        // No title or URL - fetch all reminders across lists
        NSArray *lists;
        if (listName) {
            id list = findList(store, listName);
            if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
            lists = @[list];
        } else {
            lists = fetchLists(store);
        }
        NSMutableArray *all = [NSMutableArray array];
        for (id list in lists) {
            NSArray *rems = fetchReminders(store, list, NO);
            [all addObjectsFromArray:rems];
        }
        matches = all;
    }

    // Apply tag, has-url, and notes-contains filters
    NSSet *includeTags = parseCommaSeparatedTags(tagFilter);
    NSSet *excludeTags = parseCommaSeparatedTags(excludeTagFilter);
    NSString *lowerNotesFilter = notesContains ? [notesContains lowercaseString] : nil;
    if (filterHasURL || includeTags || excludeTags || lowerNotesFilter) {
        NSMutableArray *filtered = [NSMutableArray array];
        for (id rem in matches) {
            if (filterHasURL) {
                @try {
                    id attCtx = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("attachmentContext"));
                    if (!attCtx) continue;
                    NSArray *urlAtts = ((id (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("urlAttachments"));
                    if (!urlAtts || urlAtts.count == 0) continue;
                } @catch (NSException *e) { continue; }
            }
            if (includeTags || excludeTags) {
                NSSet *remTags = getTagNames(rem);
                if (includeTags && ![includeTags intersectsSet:remTags]) continue;
                if (excludeTags && [excludeTags intersectsSet:remTags]) continue;
            }
            if (lowerNotesFilter) {
                @try {
                    NSString *notes = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
                    if (!notes || [[notes lowercaseString] rangeOfString:lowerNotesFilter].location == NSNotFound) continue;
                } @catch (NSException *e) { continue; }
            }
            [filtered addObject:rem];
        }
        matches = filtered;
    }

    if (matches.count == 0) {
        // Filter-only queries (no title/url) return empty array instead of error
        if (!title && !urlFilter) {
            printJSON(@[]);
            return 0;
        }
        NSString *desc = urlFilter ? urlFilter : title;
        errorExit([NSString stringWithFormat:@"No reminders found matching: %@", desc]);
    }

    // Skip expensive subtask expansion for bulk filter-only searches
    BOOL expandSubtasks = (title || urlFilter);
    NSMutableDictionary *listCache = expandSubtasks ? [NSMutableDictionary dictionary] : nil;
    NSMutableArray *resultArray = [NSMutableArray array];
    for (id rem in matches) {
        NSMutableDictionary *dict = [reminderToDict(rem) mutableCopy];

        if (expandSubtasks) {
            // Add subtasks (cached per list to avoid redundant fetches)
            id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
            NSString *parentIDStr = objectIDToString(parentObjID);
            id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
            NSString *listKey = objectIDToString(listID);
            NSArray *allInList = listCache[listKey];
            if (!allInList) {
                NSError *error = nil;
                allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
                    store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
                    @[listID], &error);
                if (allInList) listCache[listKey] = allInList;
            }

            NSMutableArray *subtasks = [NSMutableArray array];
            for (id sub in allInList ?: @[]) {
                id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
                if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
                    [subtasks addObject:reminderToDict(sub)];
                }
            }
            if (subtasks.count > 0) dict[@"subtasks"] = subtasks;
        }

        [resultArray addObject:dict];
    }

    if (resultArray.count == 1) {
        printJSON(resultArray[0]);
    } else {
        printJSON(resultArray);
    }
    return 0;
}

static int cmdSubtasks(id store, NSString *title, NSString *listName) {
    id rem = requireUniqueReminder(store, title, listName);

    id parentObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
    NSString *parentIDStr = objectIDToString(parentObjID);
    id listID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
    NSError *error = nil;
    NSArray *allInList = ((id (*)(id, SEL, id, id*))objc_msgSend)(
        store, sel_registerName("fetchRemindersForEventKitBridgingWithListIDs:error:"),
        @[listID], &error);

    NSMutableArray *subtasks = [NSMutableArray array];
    for (id sub in allInList) {
        id pid = ((id (*)(id, SEL))objc_msgSend)(sub, sel_registerName("parentReminderID"));
        if (pid && [objectIDToString(pid) isEqualToString:parentIDStr]) {
            [subtasks addObject:reminderToDict(sub)];
        }
    }
    printJSON(subtasks);
    return 0;
}

// Find list by objectID string. Returns nil if not found.
static id findListByObjectID(id store, id targetObjID) {
    NSArray *allLists = fetchLists(store);
    for (id l in allLists) {
        id lID = ((id (*)(id, SEL))objc_msgSend)(l, sel_registerName("objectID"));
        if ([objectIDToString(lID) isEqualToString:objectIDToString(targetObjID)]) {
            return l;
        }
    }
    return nil;
}

// Shared helper: reparent a reminder change item under a parent.
static void reparentChangeItem(id store, id saveReq, id listCI, id childCI, NSString *parentID) {
    id parentRem = findReminderByID(store, parentID);
    if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", parentID]);

    id parentCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), parentRem);

    ((void (*)(id, SEL, id, id))objc_msgSend)(
        listCI, sel_registerName("_reassignReminderChangeItem:withParentReminderChangeItem:"),
        childCI, parentCI);
}

static int cmdAdd(id store, NSString *title, NSString *listName, NSDictionary *opts) {
    id list = nil;
    NSString *parentID = opts[@"parent-id"];

    if (parentID) {
        // Look up parent to derive/validate list
        id parentRem = findReminderByID(store, parentID);
        if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", parentID]);

        id parentListID = ((id (*)(id, SEL))objc_msgSend)(parentRem, sel_registerName("listID"));
        list = findListByObjectID(store, parentListID);
        if (!list) errorExit(@"Could not find parent's list");

        // If --list was also specified, validate it matches
        if (listName) {
            id specifiedList = findList(store, listName);
            if (!specifiedList) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);
            id specListID = ((id (*)(id, SEL))objc_msgSend)(specifiedList, sel_registerName("objectID"));
            if (![objectIDToString(specListID) isEqualToString:objectIDToString(parentListID)]) {
                errorExit(@"--parent-id and --list conflict: parent is in a different list. Omit --list to auto-derive from parent.");
            }
        }
    } else {
        list = listName ? findList(store, listName) : [fetchLists(store) firstObject];
    }
    if (!list) errorExit(@"No list found");

    // Get the list change item from save request
    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    id newRem = ((id (*)(id, SEL, id, id))objc_msgSend)(
        saveReq, sel_registerName("addReminderWithTitle:toListChangeItem:"),
        title, listCI);

    if (!newRem) errorExit(@"Failed to create reminder");

    // Apply optional properties
    if (opts[@"notes"]) {
        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("setNotesAsString:"), opts[@"notes"]);
    }
    if (opts[@"completed"]) {
        BOOL val = parseBoolString(opts[@"completed"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(newRem, sel_registerName("setCompleted:"), val);
    }
    if (opts[@"priority"]) {
        NSUInteger val = [opts[@"priority"] integerValue];
        ((void (*)(id, SEL, NSUInteger))objc_msgSend)(newRem, sel_registerName("setPriority:"), val);
    }
    if (opts[@"flagged"]) {
        BOOL val = parseBoolString(opts[@"flagged"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(newRem, sel_registerName("setFlagged:"), val);
    }
    if (opts[@"due-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"due-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("setDueDateComponents:"), comps);
    }
    if (opts[@"start-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"start-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(newRem, sel_registerName("setStartDateComponents:"), comps);
    }
    if (opts[@"url"]) {
        NSURL *url = [NSURL URLWithString:opts[@"url"]];
        if (url) {
            id attCtx = ((id (*)(id, SEL))objc_msgSend)(newRem, sel_registerName("attachmentContext"));
            ((void (*)(id, SEL, id))objc_msgSend)(attCtx, sel_registerName("setURLAttachmentWithURL:"), url);
        }
    }

    // Reparent: --parent-id
    if (opts[@"parent-id"]) {
        reparentChangeItem(store, saveReq, listCI, newRem, opts[@"parent-id"]);
    }

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    // Re-fetch and return — use the resolved list name for accurate lookup
    // (when --parent-id is used without --list, listName is nil but list was derived from parent)
    NSString *resolvedListName = listName;
    if (!resolvedListName) {
        id listStorage = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("storage"));
        resolvedListName = ((id (*)(id, SEL))objc_msgSend)(listStorage, sel_registerName("name"));
    }
    id created = findReminder(store, title, resolvedListName);
    if (created) printJSON(reminderToDict(created));
    else fprintf(stderr, "Created (but could not re-fetch)\n");
    return 0;
}

static int cmdCreateList(id store, NSString *name) {
    // Get default account from the first list
    NSArray *lists = fetchLists(store);
    if (lists.count == 0) errorExit(@"No accounts found");
    id account = ((id (*)(id, SEL))objc_msgSend)(lists[0], sel_registerName("account"));

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id accountCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateAccount:"), account);

    id newList = ((id (*)(id, SEL, id, id, id))objc_msgSend)(
        saveReq, sel_registerName("addListWithName:toAccountChangeItem:listObjectID:"),
        name, accountCI, nil);

    if (!newList) errorExit(@"Failed to create list");

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"name": name, @"created": @YES});
    return 0;
}

static int cmdRenameList(id store, NSString *oldName, NSString *newName) {
    id list = findList(store, oldName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", oldName]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    id storage = ((id (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("storage"));
    ((void (*)(id, SEL, id))objc_msgSend)(storage, sel_registerName("setName:"), newName);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"oldName": oldName, @"newName": newName, @"renamed": @YES});
    return 0;
}

static int cmdDeleteList(id store, NSString *name) {
    id list = findList(store, name);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", name]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    ((void (*)(id, SEL))objc_msgSend)(listCI, sel_registerName("removeFromParent"));

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"name": name, @"deleted": @YES});
    return 0;
}

static int cmdAddTag(id store, NSString *remID, NSString *tagName) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    // Check if tag already exists (idempotent add)
    NSSet *existingTags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
    if (existingTags) {
        for (id tag in existingTags) {
            NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
            if ([name isEqualToString:tagName]) {
                // Tag already exists, return current state (no-op)
                printJSON(reminderToDict(rem));
                return 0;
            }
        }
    }

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    id hashtagCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("hashtagContext"));
    if (!hashtagCtx) errorExit(@"Failed to get hashtag context");

    // type 0 = normal tag
    ((void (*)(id, SEL, NSUInteger, id))objc_msgSend)(
        hashtagCtx, sel_registerName("addHashtagWithType:name:"), (NSUInteger)0, tagName);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    id updated = findReminderByID(store, remID);
    if (updated) printJSON(reminderToDict(updated));
    else printJSON(@{@"id": remID, @"tagAdded": tagName});
    return 0;
}

static int cmdRemoveTag(id store, NSString *remID, NSString *tagName) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    id hashtagCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("hashtagContext"));
    if (!hashtagCtx) errorExit(@"Failed to get hashtag context");

    // Find the hashtag object by name from the reminder's existing hashtags
    NSSet *tags = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("hashtags"));
    id tagToRemove = nil;
    for (id tag in tags) {
        NSString *name = ((id (*)(id, SEL))objc_msgSend)(tag, sel_registerName("name"));
        if ([name isEqualToString:tagName]) { tagToRemove = tag; break; }
    }
    if (!tagToRemove) errorExit([NSString stringWithFormat:@"Tag not found: %@", tagName]);

    ((void (*)(id, SEL, id))objc_msgSend)(hashtagCtx, sel_registerName("removeHashtag:"), tagToRemove);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    id updated = findReminderByID(store, remID);
    if (updated) printJSON(reminderToDict(updated));
    else printJSON(@{@"id": remID, @"tagRemoved": tagName});
    return 0;
}

static int cmdListSections(id store, NSString *listName) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);

    // Try to fetch sections from the list
    NSMutableArray *result = [NSMutableArray array];
    @try {
        id sections = ((id (*)(id, SEL))objc_msgSend)(list, sel_registerName("sections"));
        if (sections) {
            for (id section in sections) {
                NSString *name = ((id (*)(id, SEL))objc_msgSend)(section, sel_registerName("canonicalName"));
                id objID = ((id (*)(id, SEL))objc_msgSend)(section, sel_registerName("objectID"));
                NSMutableDictionary *d = [NSMutableDictionary dictionary];
                if (name) d[@"name"] = name;
                if (objID) d[@"id"] = objectIDToString(objID);
                [result addObject:d];
            }
        }
    } @catch (NSException *e) {
        fprintf(stderr, "Warning: could not enumerate sections: %s\n", [[e reason] UTF8String]);
    }
    printJSON(result);
    return 0;
}

static int cmdCreateSection(id store, NSString *listName, NSString *sectionName) {
    id list = findList(store, listName);
    if (!list) errorExit([NSString stringWithFormat:@"List not found: %@", listName]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateList:"), list);

    // Create a new section change item
    id newSection = ((id (*)(id, SEL, id, id, id))objc_msgSend)(
        [REMListSectionCIClass alloc],
        sel_registerName("initWithObjectID:displayName:insertIntoListChangeItem:"),
        nil, sectionName, listCI);

    if (!newSection) errorExit(@"Failed to create section");

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"list": listName, @"section": sectionName, @"created": @YES});
    return 0;
}


// --- Update Command (generated from REMINDER_WRITE_OPS) ---

static int cmdUpdate(id store, NSString *listName, NSDictionary *opts) {
    NSString *remID = opts[@"id"];
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    // Validate conflicting URL flags
    if (opts[@"url"] && opts[@"clear-url"]) {
        errorExit(@"Cannot use --url and --clear-url together");
    }

    // Validate conflicting parent flags
    NSString *parentID = opts[@"parent-id"];
    BOOL removeParent = opts[@"remove-parent"] != nil;
    if (parentID && removeParent) {
        errorExit(@"Cannot specify both --parent-id and --remove-parent");
    }

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    if (opts[@"title"]) {
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setTitleAsString:"), opts[@"title"]);
    }
    if (opts[@"append-notes"]) {
        NSString *existing = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("notesAsString"));
        NSString *combined;
        if (existing && [existing length] > 0) {
            combined = [NSString stringWithFormat:@"%@\n%@", existing, opts[@"append-notes"]];
        } else {
            combined = opts[@"append-notes"];
        }
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setNotesAsString:"), combined);
    } else if (opts[@"notes"]) {
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setNotesAsString:"), opts[@"notes"]);
    }
    if (opts[@"completed"]) {
        BOOL val = parseBoolString(opts[@"completed"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("setCompleted:"), val);
    }
    if (opts[@"priority"]) {
        NSUInteger val = [opts[@"priority"] integerValue];
        ((void (*)(id, SEL, NSUInteger))objc_msgSend)(changeItem, sel_registerName("setPriority:"), val);
    }
    if (opts[@"flagged"]) {
        BOOL val = parseBoolString(opts[@"flagged"]);
        ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("setFlagged:"), val);
    }
    if (opts[@"due-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"due-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setDueDateComponents:"), comps);
    }
    if (opts[@"start-date"]) {
        NSDateComponents *comps = stringToDateComps(opts[@"start-date"]);
        ((void (*)(id, SEL, id))objc_msgSend)(changeItem, sel_registerName("setStartDateComponents:"), comps);
    }
    if (opts[@"url"]) {
        NSURL *url = [NSURL URLWithString:opts[@"url"]];
        if (url) {
            id attCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("attachmentContext"));
            ((void (*)(id, SEL, id))objc_msgSend)(attCtx, sel_registerName("setURLAttachmentWithURL:"), url);
        }
    }
    if (opts[@"clear-url"]) {
        id attCtx = ((id (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("attachmentContext"));
        ((void (*)(id, SEL))objc_msgSend)(attCtx, sel_registerName("removeURLAttachments"));
    }
    if (opts[@"remove-parent"]) {
        ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("removeFromParentReminder"));
    }
    if (opts[@"remove-from-list"]) {
        ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("removeFromList"));
    }

    // Reparent: --parent-id
    if (parentID) {
        // Validate no self-parenting (update-specific)
        id remObjID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("objectID"));
        id parentRem = findReminderByID(store, parentID);
        if (!parentRem) errorExit([NSString stringWithFormat:@"Parent not found with id: %@", parentID]);
        id parentObjID = ((id (*)(id, SEL))objc_msgSend)(parentRem, sel_registerName("objectID"));
        if ([objectIDToString(remObjID) isEqualToString:objectIDToString(parentObjID)]) {
            errorExit(@"Cannot set a reminder as its own parent");
        }

        // Get the list for reparenting using shared helper
        id remListID = ((id (*)(id, SEL))objc_msgSend)(rem, sel_registerName("listID"));
        id targetList = findListByObjectID(store, remListID);
        if (!targetList) errorExit(@"Could not find list for reparenting");

        id listCI = ((id (*)(id, SEL, id))objc_msgSend)(
            saveReq, sel_registerName("updateList:"), targetList);

        reparentChangeItem(store, saveReq, listCI, changeItem, parentID);
    }

    // Move to different list: --to-list
    NSString *toListName = opts[@"to-list"];
    if (toListName) {
        id destList = findList(store, toListName);
        if (!destList) errorExit([NSString stringWithFormat:@"Destination list not found: %@", toListName]);

        id destListCI = ((id (*)(id, SEL, id))objc_msgSend)(
            saveReq, sel_registerName("updateList:"), destList);

        // Use initWithReminderChangeItem:insertIntoListChangeItem: to move
        Class REMReminderCIClass = NSClassFromString(@"REMReminderChangeItem");
        id moveCI = ((id (*)(id, SEL, id, id))objc_msgSend)(
            [REMReminderCIClass alloc],
            sel_registerName("initWithReminderChangeItem:insertIntoListChangeItem:"),
            changeItem, destListCI);
        if (!moveCI) errorExit(@"Failed to create move operation");
    }

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    // Re-fetch and return updated state
    id updated = findReminderByID(store, remID);
    if (updated) printJSON(reminderToDict(updated));
    else fprintf(stderr, "Updated successfully\n");
    return 0;
}


static int cmdComplete(id store, NSString *remID) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    ((void (*)(id, SEL, BOOL))objc_msgSend)(changeItem, sel_registerName("setCompleted:"), YES);

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"id": remID, @"completed": @YES});
    return 0;
}



static int cmdDelete(id store, NSString *remID) {
    id rem = findReminderByID(store, remID);
    if (!rem) errorExit([NSString stringWithFormat:@"Reminder not found with id: %@", remID]);

    id saveReq = ((id (*)(id, SEL, id))objc_msgSend)(
        [REMSaveRequestClass alloc], sel_registerName("initWithStore:"), store);

    id changeItem = ((id (*)(id, SEL, id))objc_msgSend)(
        saveReq, sel_registerName("updateReminder:"), rem);

    ((void (*)(id, SEL))objc_msgSend)(changeItem, sel_registerName("removeFromList"));

    NSError *error = nil;
    ((BOOL (*)(id, SEL, id*))objc_msgSend)(
        saveReq, sel_registerName("saveSynchronouslyWithError:"), &error);
    if (error) errorExit([NSString stringWithFormat:@"Save failed: %@", error]);

    printJSON(@{@"id": remID, @"deleted": @YES});
    return 0;
}


// --- Link Note Command ---

static int cmdLinkNote(id store, NSString *remId, NSString *noteId) {
    // Construct applenotes:// URL
    NSURLComponents *comps = [[NSURLComponents alloc] init];
    comps.scheme = @"applenotes";
    comps.host = @"showNote";
    comps.queryItems = @[[NSURLQueryItem queryItemWithName:@"identifier" value:noteId]];
    NSString *urlStr = [comps string];

    // Delegate to cmdUpdate with the constructed URL
    return cmdUpdate(store, nil, @{@"id": remId, @"url": urlStr});
}

